import type { SeedEvent } from '../types'

/**
 * Eventos y lugares emblemáticos del resto de Chile, por región.
 * Coordenadas verificadas contra direcciones conocidas.
 * Datos placeholder MVP: la curación final debe validarse antes de uso público.
 */

const MC = (slug: string, topic: string) => ({
  type: 'MEMORIA_CHILENA' as const,
  title: `Memoria Chilena — ${topic}`,
  url: `https://www.memoriachilena.gob.cl/602/w3-search.html?q=${encodeURIComponent(slug)}`,
  citation: `Memoria Chilena (s.f.). ${topic}. Biblioteca Nacional Digital de Chile.`,
})

const BN = (title: string, author: string, year: number, signature?: string) => ({
  type: 'BIBLIOTECA_NACIONAL' as const,
  title,
  author,
  year,
  ...(signature ? { signature } : {}),
  citation: `${author} (${year}). ${title}. Biblioteca Nacional de Chile${signature ? `, ${signature}` : ''}.`,
  inPublicDomain: year < 1925,
})

const CMN = (topic: string, year?: number) => ({
  type: 'ARCHIVO_NACIONAL' as const,
  title: `Consejo de Monumentos Nacionales — ${topic}`,
  citation: `Consejo de Monumentos Nacionales${year ? ` (${year})` : ''}. ${topic}. Ministerio de las Culturas.`,
  inPublicDomain: true,
})

export const CHILE_REGIONES: SeedEvent[] = [
  // =========================================================================
  // ARICA Y PARINACOTA
  // =========================================================================
  {
    slug: 'arica-fundacion-1541',
    title: 'Fundación de Arica',
    shortDesc: 'Lucas Martínez Vegaso funda San Marcos de Arica el 25 de abril de 1541.',
    longDesc:
      'San Marcos de Arica fue fundada por el capitán Lucas Martínez Vegaso por orden del Marqués de Casaconcha, gobernador del Perú, el 25 de abril de 1541. Originalmente puerto del Virreinato del Perú, pasó a Chile tras la Guerra del Pacífico (Tratado de Lima, 1929). Es la ciudad más septentrional de Chile y entrada al norte grande. Su catedral San Marcos fue diseñada por Gustave Eiffel.',
    yearStart: 1541,
    dateText: '25 de abril de 1541',
    category: 'FUNDACION',
    era: 'CONQUISTA',
    latitude: -18.4783,
    longitude: -70.3126,
    region: 'Arica y Parinacota',
    comuna: 'Arica',
    sources: [MC('arica', 'Historia de Arica')],
  },
  {
    slug: 'catedral-san-marcos-arica-1876',
    title: 'Catedral de San Marcos de Arica',
    shortDesc: 'Iglesia metálica diseñada por Gustave Eiffel e inaugurada en 1876.',
    longDesc:
      'La Catedral San Marcos de Arica es una de las pocas iglesias construidas íntegramente en metal en el mundo. Diseñada por el taller de Gustave Eiffel en París, fue prefabricada en piezas y armada in situ. Fue inaugurada el 14 de julio de 1876, financiada por el gobierno peruano tras el terremoto de 1868 que destruyó la anterior. Es Monumento Histórico desde 1984.',
    yearStart: 1876,
    dateText: '14 de julio de 1876',
    category: 'RELIGION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -18.4761,
    longitude: -70.3214,
    region: 'Arica y Parinacota',
    comuna: 'Arica',
    sources: [CMN('Catedral de San Marcos', 1984)],
  },
  {
    slug: 'morro-arica-1880',
    title: 'Asalto y toma del Morro de Arica',
    shortDesc: 'El 7 de junio de 1880 el ejército chileno toma el Morro de Arica en 55 minutos.',
    longDesc:
      'En el contexto de la Guerra del Pacífico, el 7 de junio de 1880 las tropas chilenas al mando del coronel Pedro Lagos asaltaron el Morro de Arica, defendido por el coronel peruano Francisco Bolognesi. El combate duró 55 minutos. Bolognesi murió tras la frase "Hasta quemar el último cartucho". La toma del Morro selló el dominio chileno del litoral tras la guerra. Hoy es Monumento Nacional con museo.',
    yearStart: 1880,
    dateText: '7 de junio de 1880',
    category: 'BATALLA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -18.4839,
    longitude: -70.3214,
    region: 'Arica y Parinacota',
    comuna: 'Arica',
    featured: true,
    sources: [BN('Historia de la Guerra del Pacífico', 'Gonzalo Bulnes', 1911, 'BN-985-B936')],
  },
  {
    slug: 'chinchorro-momias',
    title: 'Cultura Chinchorro: las momias más antiguas del mundo',
    shortDesc: 'Las momias de la cultura Chinchorro (7000-1100 a.C.) son las más antiguas del mundo.',
    longDesc:
      'La cultura Chinchorro, que habitó la costa entre Ilo (Perú) y Antofagasta (Chile) desde aproximadamente 7.000 a 1.100 a.C., desarrolló la práctica de momificación artificial más antigua conocida en el mundo, anterior a los egipcios en 2.000 años. Sus momias —incluidas las de niños— se preparaban con técnicas complejas. En 2021 la cultura fue declarada Patrimonio de la Humanidad por la UNESCO. Se exhiben en el Museo Universidad de Tarapacá San Miguel de Azapa.',
    yearStart: -7000,
    yearEnd: -1100,
    category: 'PUEBLOS_ORIGINARIOS',
    era: 'PREHISPANICA',
    latitude: -18.5181,
    longitude: -70.2389,
    region: 'Arica y Parinacota',
    comuna: 'Arica',
    featured: true,
    sources: [MC('chinchorro', 'Cultura Chinchorro')],
  },
  {
    slug: 'parinacota-iglesia-1789',
    title: 'Iglesia de Parinacota',
    shortDesc: 'Iglesia altiplánica del siglo XVIII, una de las más antiguas del norte chileno.',
    longDesc:
      'La Iglesia de Parinacota, en el poblado homónimo a 4.400 msnm, fue construida en 1789 sobre fundaciones más antiguas. De adobe pintada de blanco y techo de paja, conserva pinturas murales coloniales únicas. Está dentro del Parque Nacional Lauca. Es Monumento Nacional desde 1979 e ícono del barroco altiplánico.',
    yearStart: 1789,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -18.2,
    longitude: -69.275,
    region: 'Arica y Parinacota',
    comuna: 'Putre',
    sources: [CMN('Iglesia de Parinacota', 1979)],
  },

  // =========================================================================
  // TARAPACÁ
  // =========================================================================
  {
    slug: 'iquique-fundacion-1830',
    title: 'Fundación moderna de Iquique',
    shortDesc: 'Iquique como puerto se desarrolla con el auge del salitre desde 1830.',
    longDesc:
      'Iquique era una pequeña caleta cuando, hacia 1830, comenzó el auge del salitre que la convertiría en uno de los puertos más importantes del Pacífico sur. Era territorio peruano hasta la Guerra del Pacífico. Sus casas estilo georgiano de pinotea importada (Casino Español, Palacio Astoreca, Teatro Municipal) testimonian su esplendor. Fue capital salitrera del mundo entre 1880 y 1930.',
    yearStart: 1830,
    category: 'ECONOMIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -20.2308,
    longitude: -70.1356,
    region: 'Tarapacá',
    comuna: 'Iquique',
    sources: [MC('iquique', 'Historia de Iquique')],
  },
  {
    slug: 'combate-iquique-1879',
    title: 'Combate Naval de Iquique',
    shortDesc: 'El 21 de mayo de 1879 muere Arturo Prat en el Combate Naval de Iquique.',
    longDesc:
      'En la bahía de Iquique, el 21 de mayo de 1879, la fragata peruana Huáscar hundió a la corbeta chilena Esmeralda. Su capitán Arturo Prat Chacón se lanzó al abordaje y murió. La fecha es feriado nacional como "Día de las Glorias Navales". Una boya en la bahía marca el sitio del hundimiento. Es uno de los eventos más conmemorados de la historia chilena.',
    yearStart: 1879,
    dateText: '21 de mayo de 1879',
    category: 'BATALLA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -20.2128,
    longitude: -70.1556,
    region: 'Tarapacá',
    comuna: 'Iquique',
    featured: true,
    sources: [BN('Crónica de la Guerra del Pacífico', 'Gonzalo Bulnes', 1911)],
  },
  {
    slug: 'matanza-santa-maria-iquique-1907',
    title: 'Matanza de Santa María de Iquique',
    shortDesc: 'El 21 de diciembre de 1907 el ejército masacra a obreros del salitre en huelga.',
    longDesc:
      'Tras semanas de huelga de obreros del salitre, miles de trabajadores con sus familias se concentraron en la Escuela Santa María de Iquique. El 21 de diciembre de 1907, por orden del general Roberto Silva Renard, las tropas abrieron fuego sobre los huelguistas. Murieron entre 2.000 y 3.600 personas. La masacre es uno de los hitos más oscuros de la historia obrera chilena. Inspiró la cantata de Luis Advis (1969).',
    yearStart: 1907,
    dateText: '21 de diciembre de 1907',
    category: 'POLITICA',
    era: 'PARLAMENTARISMO',
    latitude: -20.2156,
    longitude: -70.1422,
    region: 'Tarapacá',
    comuna: 'Iquique',
    featured: true,
    sources: [
      BN('Hijo del salitre', 'Volodia Teitelboim', 1952),
      MC('santa-maria-iquique', 'Matanza de Santa María'),
    ],
  },
  {
    slug: 'palacio-astoreca-1903',
    title: 'Palacio Astoreca',
    shortDesc: 'Mansión salitrera de 1903 en Iquique, hoy museo.',
    longDesc:
      'El Palacio Astoreca, en calle O\'Higgins 350 de Iquique, fue construido en 1903 por el empresario salitrero Juan Higinio Astoreca. Diseño afrancesado con pinotea de Oregón, vitrales y revestimientos europeos. Tras décadas de abandono fue restaurado y reabierto en 1980 como museo. Es Monumento Histórico.',
    yearStart: 1903,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -20.214,
    longitude: -70.1505,
    region: 'Tarapacá',
    comuna: 'Iquique',
    sources: [CMN('Palacio Astoreca', 1977)],
  },
  {
    slug: 'teatro-municipal-iquique-1890',
    title: 'Teatro Municipal de Iquique',
    shortDesc: 'Teatro neoclásico inaugurado en 1890 en pleno boom salitrero.',
    longDesc:
      'El Teatro Municipal de Iquique se inauguró el 1 de octubre de 1890. Diseñado por el arquitecto napolitano Eduardo Vallenari Hicke, su frontis tetrástilo con cariátides representa las cuatro estaciones. En su apogeo recibió a las principales compañías líricas y artistas europeos que pasaban por el Pacífico. Es Monumento Histórico.',
    yearStart: 1890,
    dateText: '1 de octubre de 1890',
    category: 'CULTURA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -20.2147,
    longitude: -70.1517,
    region: 'Tarapacá',
    comuna: 'Iquique',
    sources: [MC('teatro-iquique', 'Teatro Municipal de Iquique')],
  },

  // =========================================================================
  // ANTOFAGASTA
  // =========================================================================
  {
    slug: 'antofagasta-fundacion-1868',
    title: 'Fundación de Antofagasta',
    shortDesc: 'La caleta "La Chimba" se transforma en puerto salitrero en 1868.',
    longDesc:
      'El descubrimiento de salitre en 1866 transformó la caleta "La Chimba" en el puerto Antofagasta. Originalmente boliviana, fue ocupada por Chile el 14 de febrero de 1879 (acto que detonó la Guerra del Pacífico). Tras el Tratado de Paz y Amistad de 1904, pasó definitivamente a Chile. Es la capital del Norte Grande y centro de la minería del cobre y litio.',
    yearStart: 1868,
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -23.65,
    longitude: -70.4,
    region: 'Antofagasta',
    comuna: 'Antofagasta',
    sources: [MC('antofagasta', 'Historia de Antofagasta')],
  },
  {
    slug: 'ocupacion-antofagasta-1879',
    title: 'Ocupación chilena de Antofagasta',
    shortDesc: 'El 14 de febrero de 1879 las tropas chilenas desembarcan en Antofagasta, iniciando la Guerra del Pacífico.',
    longDesc:
      'Tras el aumento del impuesto al salitre por Bolivia que afectaba a la Compañía de Salitres y Ferrocarril de Antofagasta, el ejército chileno desembarcó en Antofagasta el 14 de febrero de 1879. La acción detonó la Guerra del Pacífico contra Perú y Bolivia. Tras la victoria chilena, el territorio quedó definitivamente bajo soberanía nacional por el Tratado de Paz de 1904.',
    yearStart: 1879,
    dateText: '14 de febrero de 1879',
    category: 'BATALLA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -23.6509,
    longitude: -70.3975,
    region: 'Antofagasta',
    comuna: 'Antofagasta',
    sources: [BN('Historia de la Guerra del Pacífico', 'Gonzalo Bulnes', 1911)],
  },
  {
    slug: 'la-portada-antofagasta',
    title: 'Monumento natural La Portada',
    shortDesc: 'Arco natural emblemático de la costa de Antofagasta, declarado Monumento Natural en 1990.',
    longDesc:
      'La Portada es un arco natural de roca sedimentaria de 43 metros de altura ubicado 18 km al norte de Antofagasta. Su forma característica la hizo emblema de la región. Fue declarada Monumento Natural en 1990. Forma parte del Parque Nacional Morro Moreno. Su deterioro por erosión es objeto de monitoreo permanente.',
    yearStart: 1990,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -23.5158,
    longitude: -70.4286,
    region: 'Antofagasta',
    comuna: 'Antofagasta',
    sources: [CMN('La Portada', 1990)],
  },
  {
    slug: 'mineria-chuquicamata-1915',
    title: 'Mina Chuquicamata',
    shortDesc: 'La mina de cobre a tajo abierto más grande del mundo, en operación industrial desde 1915.',
    longDesc:
      'La mina Chuquicamata fue explotada por las culturas atacameñas desde tiempos prehispánicos. La explotación industrial moderna comenzó en 1915 por la Chile Exploration Company (después Anaconda). Nacionalizada por Salvador Allende en 1971, pasó a Codelco. Es la mina de cobre a tajo abierto más grande del mundo: 4,5 km de largo, 3,7 km de ancho, 850 metros de profundidad. El campamento histórico fue cerrado en 2007.',
    yearStart: 1915,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -22.2856,
    longitude: -68.9028,
    region: 'Antofagasta',
    comuna: 'Calama',
    featured: true,
    sources: [MC('chuquicamata', 'Mina Chuquicamata')],
  },
  {
    slug: 'san-pedro-atacama-iglesia',
    title: 'Iglesia de San Pedro de Atacama',
    shortDesc: 'Iglesia colonial de 1745 en el corazón del oasis atacameño.',
    longDesc:
      'La Iglesia de San Pedro de Atacama fue construida en 1745 (con elementos del XVII) en el centro del oasis. De adobe blanco con techo de cardón, es uno de los templos andinos mejor conservados. Custodia imágenes coloniales. Es Monumento Histórico desde 1951.',
    yearStart: 1745,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -22.9092,
    longitude: -68.2,
    region: 'Antofagasta',
    comuna: 'San Pedro de Atacama',
    sources: [CMN('Iglesia San Pedro', 1951)],
  },
  {
    slug: 'tulor-aldea-prehispanica',
    title: 'Aldea de Tulor',
    shortDesc: 'Asentamiento prehispánico de 800 a.C. cerca de San Pedro de Atacama.',
    longDesc:
      'La Aldea de Tulor, a 9 km al sur de San Pedro de Atacama, es uno de los asentamientos atacameños más antiguos conocidos, datado entre 800 a.C. y 500 d.C. Sus estructuras circulares de adobe forman un conjunto urbano sin precedentes en la zona. Fue parcialmente sepultada por arena y la urbanización moderna. Está abierta al público bajo gestión del Museo Le Paige.',
    yearStart: -800,
    yearEnd: 500,
    category: 'PUEBLOS_ORIGINARIOS',
    era: 'PREHISPANICA',
    latitude: -22.9819,
    longitude: -68.1731,
    region: 'Antofagasta',
    comuna: 'San Pedro de Atacama',
    sources: [MC('tulor', 'Aldea de Tulor')],
  },

  // =========================================================================
  // ATACAMA
  // =========================================================================
  {
    slug: 'copiapo-fundacion-1744',
    title: 'Fundación de Copiapó',
    shortDesc: 'San Francisco de la Selva de Copiapó fue fundada el 8 de diciembre de 1744.',
    longDesc:
      'El gobernador Domingo Ortiz de Rozas funda la villa San Francisco de la Selva de Copiapó el 8 de diciembre de 1744 sobre un asentamiento diaguita. La región alberga grandes yacimientos minerales (plata desde Chañarcillo, cobre y oro). Copiapó fue la primera ciudad sudamericana con ferrocarril (1851, a Caldera) y con alumbrado a gas (1858).',
    yearStart: 1744,
    dateText: '8 de diciembre de 1744',
    category: 'FUNDACION',
    era: 'COLONIA',
    latitude: -27.3666,
    longitude: -70.3322,
    region: 'Atacama',
    comuna: 'Copiapó',
    sources: [MC('copiapo', 'Historia de Copiapó')],
  },
  {
    slug: 'chanarcillo-1832',
    title: 'Descubrimiento de Chañarcillo',
    shortDesc: 'En 1832 Juan Godoy descubre el yacimiento de plata de Chañarcillo, mayor mina de plata sudamericana del siglo XIX.',
    longDesc:
      'El 16 de mayo de 1832, el arriero Juan Godoy descubrió en la sierra de Chañarcillo (cerca de Copiapó) el mayor yacimiento de plata de Sudamérica del XIX. La producción de plata enriqueció a las familias Cousiño, Edwards, Gallo, Matta, que financiaron el desarrollo industrial chileno. La fortuna del salitre se construyó sobre la del salitre y sobre Chañarcillo. La mina cerró en 1888.',
    yearStart: 1832,
    yearEnd: 1888,
    dateText: '16 de mayo de 1832',
    category: 'ECONOMIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -27.85,
    longitude: -70.25,
    region: 'Atacama',
    comuna: 'Tierra Amarilla',
    sources: [MC('chanarcillo', 'Mina de plata de Chañarcillo')],
  },
  {
    slug: 'ferrocarril-copiapo-caldera-1851',
    title: 'Primer ferrocarril de Sudamérica',
    shortDesc: 'El 25 de diciembre de 1851 corre el primer ferrocarril sudamericano: Copiapó-Caldera.',
    longDesc:
      'Diseñado por el ingeniero norteamericano William Wheelwright, el ferrocarril Copiapó-Caldera fue el primero de Sudamérica. Inaugurado el 25 de diciembre de 1851 con 81 km, transportaba minerales de Chañarcillo al puerto de Caldera. Antecede en 5 años al primer ferrocarril español. Sus locomotoras (la "Copiapó" de 1850) se conservan en el Museo Ferroviario de Santiago.',
    yearStart: 1851,
    dateText: '25 de diciembre de 1851',
    category: 'TRANSPORTE',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -27.0667,
    longitude: -70.8222,
    region: 'Atacama',
    comuna: 'Caldera',
    sources: [BN('Los ferrocarriles de Chile', 'Santiago Marín Vicuña', 1916)],
  },

  // =========================================================================
  // COQUIMBO
  // =========================================================================
  {
    slug: 'la-serena-fundacion-1544',
    title: 'Fundación de La Serena',
    shortDesc: 'Juan Bohón funda San Bartolomé de La Serena el 26 de agosto de 1544.',
    longDesc:
      'Juan Bohón, por orden de Pedro de Valdivia, fundó San Bartolomé de La Serena el 26 de agosto de 1544 como punto de relevo entre Santiago y el Perú. Destruida por los diaguitas en 1549, fue refundada en 1552 por Francisco de Aguirre. Es la segunda ciudad más antigua de Chile (después de Santiago) y conserva un casco histórico colonial-republicano único, con 29 iglesias.',
    yearStart: 1544,
    dateText: '26 de agosto de 1544',
    category: 'FUNDACION',
    era: 'CONQUISTA',
    latitude: -29.9027,
    longitude: -71.2519,
    region: 'Coquimbo',
    comuna: 'La Serena',
    sources: [MC('la-serena', 'Historia de La Serena')],
  },
  {
    slug: 'catedral-la-serena-1844',
    title: 'Catedral de La Serena',
    shortDesc: 'Construida entre 1844 y 1856, con piedra caliza de la región.',
    longDesc:
      'La Catedral de La Serena fue diseñada por el arquitecto francés Juan Herbage y construida entre 1844 y 1856 con piedra caliza. Su estilo neoclásico, su frontis de tres columnas dóricas y su torre principal de 39 metros la convirtieron en hito urbano. Es Monumento Histórico desde 1981.',
    yearStart: 1844,
    yearEnd: 1856,
    category: 'RELIGION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -29.9046,
    longitude: -71.2511,
    region: 'Coquimbo',
    comuna: 'La Serena',
    sources: [CMN('Catedral La Serena', 1981)],
  },
  {
    slug: 'coquimbo-fundacion-1879',
    title: 'Fundación moderna de Coquimbo',
    shortDesc: 'Coquimbo se constituye como ciudad en 1879, ya como puerto activo.',
    longDesc:
      'Aunque la bahía de Coquimbo fue puerto natural desde el XVI, la ciudad como tal se constituyó por ley el 5 de octubre de 1879. Su barrio inglés con casas de pinotea y su elevado Mirador de Coquimbo (Cruz del Tercer Milenio, 93 m, inaugurada en el 2000) son hitos. Es el principal puerto de la región de Coquimbo.',
    yearStart: 1879,
    dateText: '5 de octubre de 1879',
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -29.9533,
    longitude: -71.3436,
    region: 'Coquimbo',
    comuna: 'Coquimbo',
    sources: [MC('coquimbo', 'Historia de Coquimbo')],
  },
  {
    slug: 'observatorio-tololo-1965',
    title: 'Observatorio Interamericano Cerro Tololo',
    shortDesc: 'Inaugurado en 1965, primer observatorio internacional grande de Chile.',
    longDesc:
      'El Observatorio Interamericano de Cerro Tololo se inauguró en 1965 a 80 km al este de La Serena, a 2.200 msnm. Su telescopio Blanco de 4 metros (1974) fue por años el más grande del hemisferio sur. Inauguró la era de la astronomía moderna en Chile, hoy hogar del 40% de la capacidad astronómica mundial. Es operado por NOAO-AURA con apoyo de NSF.',
    yearStart: 1965,
    category: 'CIENCIA',
    era: 'PRESIDENCIALISMO',
    latitude: -30.1697,
    longitude: -70.8067,
    region: 'Coquimbo',
    comuna: 'Vicuña',
    featured: true,
    sources: [MC('tololo', 'Observatorio Cerro Tololo')],
  },
  {
    slug: 'pisco-elqui-mistral',
    title: 'Casa-Museo Gabriela Mistral en Vicuña',
    shortDesc: 'Casa natal de la poeta Gabriela Mistral en Vicuña (1889).',
    longDesc:
      'En la calle Gabriela Mistral 759 de Vicuña, está la casa natal donde nació Lucila Godoy Alcayaga (Gabriela Mistral) el 7 de abril de 1889. Hoy es museo administrado por la Fundación Premio Nobel Gabriela Mistral. Conserva mobiliario, manuscritos, fotografías y la medalla del Nobel de Literatura 1945. Está cerca de su tumba en Montegrande.',
    yearStart: 1889,
    dateText: '7 de abril de 1889',
    category: 'CULTURA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -30.0303,
    longitude: -70.7106,
    region: 'Coquimbo',
    comuna: 'Vicuña',
    sources: [MC('mistral-vicuna', 'Gabriela Mistral')],
  },

  // =========================================================================
  // VALPARAÍSO (refuerzo + región)
  // =========================================================================
  {
    slug: 'ascensor-concepcion-1883-extra',
    title: 'Ascensor Concepción',
    shortDesc: 'Primer ascensor de Valparaíso, inaugurado el 1 de diciembre de 1883.',
    longDesc:
      'El Ascensor Concepción (también conocido como "Turri") es el más antiguo de Valparaíso, inaugurado el 1 de diciembre de 1883. Conecta la calle Esmeralda en el plan con el Paseo Gervasoni en el cerro Concepción. Tiene una pendiente de 45° y un desnivel de 50 metros. Es Monumento Histórico desde 1976 y parte del conjunto Patrimonio de la Humanidad.',
    yearStart: 1883,
    dateText: '1 de diciembre de 1883',
    category: 'TRANSPORTE',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.0408,
    longitude: -71.6253,
    region: 'Valparaíso',
    comuna: 'Valparaíso',
    sources: [CMN('Ascensor Concepción', 1976)],
  },
  {
    slug: 'reloj-turri',
    title: 'Reloj Turri',
    shortDesc: 'Edificio emblemático con reloj de 1923 en el plan de Valparaíso.',
    longDesc:
      'El Edificio Turri, en Esmeralda con Prat de Valparaíso, fue construido en 1923 para la familia Turri (de origen italiano). Su torre de reloj de cuatro caras se convirtió en uno de los símbolos del plan porteño. Diseño de Renato Schiavon. Es Monumento Histórico.',
    yearStart: 1923,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.0395,
    longitude: -71.6261,
    region: 'Valparaíso',
    comuna: 'Valparaíso',
    sources: [MC('edificio-turri', 'Edificio Turri')],
  },
  {
    slug: 'palacio-baburizza-1916',
    title: 'Palacio Baburizza',
    shortDesc: 'Mansión Art Nouveau de 1916 en cerro Alegre, hoy Museo de Bellas Artes de Valparaíso.',
    longDesc:
      'El Palacio Baburizza, en el Paseo Yugoslavo del cerro Alegre, fue construido en 1916 por el arquitecto italiano Arnaldo Barison para la familia Zanelli. Después fue del croata Pascual Baburizza, magnate del salitre. En 1971 fue donado al municipio y reabierto en 2012 como Museo de Bellas Artes. Es Monumento Histórico.',
    yearStart: 1916,
    category: 'CULTURA',
    era: 'PARLAMENTARISMO',
    latitude: -33.0394,
    longitude: -71.6244,
    region: 'Valparaíso',
    comuna: 'Valparaíso',
    sources: [CMN('Palacio Baburizza', 1979)],
  },
  {
    slug: 'iglesia-matriz-valparaiso',
    title: 'Iglesia La Matriz',
    shortDesc: 'La iglesia más antigua de Valparaíso, fundada en 1559.',
    longDesc:
      'La Iglesia La Matriz del Salvador, en Plaza Echaurren del barrio Puerto, fue fundada por Rodrigo González Marmolejo en 1559. La edificación actual es la cuarta (1842) tras destrucciones por piratas y terremotos. Su torre de 22 metros domina el casco antiguo. Es la iglesia más antigua de Valparaíso. Monumento Histórico desde 1971.',
    yearStart: 1842,
    category: 'RELIGION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.0381,
    longitude: -71.6306,
    region: 'Valparaíso',
    comuna: 'Valparaíso',
    sources: [CMN('La Matriz', 1971)],
  },
  {
    slug: 'congreso-nacional-valparaiso',
    title: 'Congreso Nacional de Valparaíso',
    shortDesc: 'Sede del Congreso desde 1990, en pleno barrio Almendral.',
    longDesc:
      'El Congreso Nacional de Chile se trasladó a Valparaíso en 1990 tras la vuelta a la democracia, por decisión de Pinochet en 1988 (DL 18.918). Su nuevo edificio en Av. Pedro Montt con Rawson fue inaugurado en 1990. Hoy alberga la Cámara de Diputados y el Senado. Su diseño postmoderno ha sido criticado pero su funcionamiento es estable.',
    yearStart: 1990,
    category: 'POLITICA',
    era: 'TRANSICION',
    latitude: -33.0467,
    longitude: -71.6147,
    region: 'Valparaíso',
    comuna: 'Valparaíso',
    sources: [MC('congreso-valparaiso', 'Congreso Nacional')],
  },
  {
    slug: 'casa-la-sebastiana-neruda',
    title: 'La Sebastiana, casa de Neruda en Valparaíso',
    shortDesc: 'Casa-museo de Pablo Neruda en el cerro Bellavista de Valparaíso.',
    longDesc:
      'Pablo Neruda compró en 1959 una casa inconclusa de Sebastián Collado (de ahí "La Sebastiana") en Valparaíso. La habitó entre 1961 y su muerte en 1973. Cinco pisos con vista panorámica a la bahía. Hoy es museo administrado por la Fundación Neruda. Está en Ferrari 692, cerro Bellavista.',
    yearStart: 1961,
    yearEnd: 1973,
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.0466,
    longitude: -71.6056,
    region: 'Valparaíso',
    comuna: 'Valparaíso',
    sources: [BN('Las casas de Neruda', 'Hernán Loyola', 1990)],
  },
  {
    slug: 'casa-isla-negra-neruda',
    title: 'Casa de Isla Negra',
    shortDesc: 'Casa principal y refugio creativo de Pablo Neruda, frente al Pacífico.',
    longDesc:
      'En Isla Negra (comuna de El Quisco), Pablo Neruda construyó desde 1939 su casa principal. Allí escribió la mayoría de su obra madura, incluido "Canto General". La casa contiene su colección de mascarones de proa, conchas y figuras náuticas. Está enterrado allí junto a Matilde Urrutia desde 1992. Hoy es museo abierto al público.',
    yearStart: 1939,
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4047,
    longitude: -71.6961,
    region: 'Valparaíso',
    comuna: 'El Quisco',
    featured: true,
    sources: [BN('Las casas de Neruda', 'Hernán Loyola', 1990)],
  },
  {
    slug: 'vina-del-mar-1874',
    title: 'Fundación de Viña del Mar',
    shortDesc: 'Viña del Mar se constituye como villa el 30 de mayo de 1874.',
    longDesc:
      'Viña del Mar fue fundada como villa el 30 de mayo de 1874 sobre los terrenos de Francisco Álvarez. Su desarrollo como balneario de las elites de Valparaíso y Santiago la consolidó como "La Ciudad Jardín". El Casino Municipal (1930) y el Festival de la Canción (1960) son sus hitos modernos. Es una de las ciudades más visitadas de Chile.',
    yearStart: 1874,
    dateText: '30 de mayo de 1874',
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.0245,
    longitude: -71.5518,
    region: 'Valparaíso',
    comuna: 'Viña del Mar',
    sources: [MC('vina-del-mar', 'Historia de Viña del Mar')],
  },
  {
    slug: 'casino-vina-1930',
    title: 'Casino Municipal de Viña del Mar',
    shortDesc: 'Inaugurado el 31 de diciembre de 1930, primer casino de Sudamérica.',
    longDesc:
      'El Casino Municipal de Viña del Mar se inauguró el 31 de diciembre de 1930. Diseño art decó del arquitecto chileno Eduardo Provasoli y el francés Henri Cooner. Por décadas el más glamoroso de Sudamérica. Operó sin interrupciones hasta hoy. Es Monumento Histórico desde 2008.',
    yearStart: 1930,
    dateText: '31 de diciembre de 1930',
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.0203,
    longitude: -71.5408,
    region: 'Valparaíso',
    comuna: 'Viña del Mar',
    sources: [CMN('Casino Viña del Mar', 2008)],
  },
  {
    slug: 'quinta-vergara-1860',
    title: 'Quinta Vergara',
    shortDesc: 'Parque y palacio de la familia Vergara, sede del Festival de la Canción.',
    longDesc:
      'La Quinta Vergara, en pleno centro de Viña del Mar, era propiedad de la familia Vergara Álvarez. Su palacio (1908-1910) es Museo de Bellas Artes desde 1941. El anfiteatro construido en 1959 es sede del Festival Internacional de la Canción desde 1960. Es Monumento Histórico.',
    yearStart: 1908,
    category: 'CULTURA',
    era: 'PARLAMENTARISMO',
    latitude: -33.0264,
    longitude: -71.5494,
    region: 'Valparaíso',
    comuna: 'Viña del Mar',
    sources: [CMN('Quinta Vergara', 1990)],
  },
  {
    slug: 'rapa-nui-moai',
    title: 'Moai de Rapa Nui',
    shortDesc: 'Estatuas monolíticas levantadas entre 1250 y 1500 en la Isla de Pascua.',
    longDesc:
      'Los moai son estatuas monolíticas talladas por los Rapa Nui entre los siglos XIII y XVI. Cerca de 1.000 piezas, algunas de hasta 10 m y 80 toneladas, fueron talladas en el cráter Rano Raraku y trasladadas a "ahu" (plataformas ceremoniales) en la costa. La civilización Rapa Nui colapsó hacia 1700 por deforestación y luchas internas. La isla fue anexada a Chile en 1888. Es Patrimonio de la Humanidad desde 1995.',
    yearStart: 1250,
    yearEnd: 1500,
    category: 'PUEBLOS_ORIGINARIOS',
    era: 'PREHISPANICA',
    latitude: -27.1212,
    longitude: -109.2895,
    region: 'Valparaíso',
    comuna: 'Isla de Pascua',
    featured: true,
    sources: [
      BN('Easter Island archaeology', 'Thor Heyerdahl', 1958),
      MC('rapa-nui', 'Isla de Pascua'),
    ],
  },
  {
    slug: 'anexion-isla-pascua-1888',
    title: 'Anexión de Rapa Nui a Chile',
    shortDesc: 'El 9 de septiembre de 1888 Chile anexa Isla de Pascua mediante acuerdo con el rey Atamu Tekena.',
    longDesc:
      'El capitán Policarpo Toro firmó el 9 de septiembre de 1888 con el rey Rapa Nui Atamu Tekena el "Acuerdo de Voluntades" por el cual Isla de Pascua pasaba a soberanía chilena. La isla fue arrendada como hacienda ovina por décadas, lo que oprimió a la población rapanui. En 1966 fue declarada departamento chileno con plenos derechos. Hoy es territorio especial.',
    yearStart: 1888,
    dateText: '9 de septiembre de 1888',
    category: 'POLITICA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -27.1505,
    longitude: -109.4267,
    region: 'Valparaíso',
    comuna: 'Isla de Pascua',
    sources: [BN('Historia de Rapa Nui', 'Cristián Moreno Pakarati', 2010)],
  },
  {
    slug: 'isla-juan-fernandez-defoe',
    title: 'Isla Robinson Crusoe',
    shortDesc: 'Isla del archipiélago Juan Fernández, refugio del marinero Alexander Selkirk (1704-1709).',
    longDesc:
      'La Isla Más a Tierra (renombrada Robinson Crusoe en 1966) fue donde el marinero escocés Alexander Selkirk vivió como náufrago entre 1704 y 1709. Su historia inspiró la novela "Robinson Crusoe" de Daniel Defoe (1719). Forma parte del Parque Nacional Juan Fernández, Reserva de la Biosfera UNESCO. Tiene 600 habitantes y endemismos vegetales únicos.',
    yearStart: 1704,
    yearEnd: 1709,
    category: 'CULTURA',
    era: 'COLONIA',
    latitude: -33.6378,
    longitude: -78.8294,
    region: 'Valparaíso',
    comuna: 'Juan Fernández',
    sources: [MC('robinson-crusoe', 'Isla Robinson Crusoe')],
  },

  // =========================================================================
  // O'HIGGINS / MAULE
  // =========================================================================
  {
    slug: 'rancagua-batalla-1814',
    title: 'Desastre de Rancagua',
    shortDesc: 'El 1 y 2 de octubre de 1814 los patriotas son derrotados en Rancagua.',
    longDesc:
      'En la Batalla de Rancagua del 1 y 2 de octubre de 1814, el ejército patriota al mando de Bernardo O\'Higgins fue cercado en la plaza de Rancagua por tropas realistas. Tras agotar las municiones, los sobrevivientes (300 de 1.500) huyeron a Mendoza. El desastre puso fin a la Patria Vieja e inició el período de la Reconquista. Hoy una placa en la plaza recuerda el evento.',
    yearStart: 1814,
    dateText: '1 y 2 de octubre de 1814',
    category: 'BATALLA',
    era: 'INDEPENDENCIA',
    latitude: -34.1708,
    longitude: -70.7406,
    region: "O'Higgins",
    comuna: 'Rancagua',
    sources: [BN('La Patria Vieja', 'Diego Barros Arana', 1888)],
  },
  {
    slug: 'sewell-1906',
    title: 'Campamento Sewell',
    shortDesc: 'Ciudad minera de El Teniente, en operación entre 1906 y 1980. Patrimonio UNESCO.',
    longDesc:
      'Sewell, "la ciudad de las escaleras", fue construido desde 1906 a 2.250 msnm en la cordillera de O\'Higgins para albergar a los trabajadores de la mina de cobre El Teniente. Llegó a tener 16.000 habitantes. Sus edificios de madera pintada y sus escaleras (no había calles para vehículos) la hicieron única. Cerró como campamento en 1980. En 2006 fue declarado Patrimonio de la Humanidad.',
    yearStart: 1906,
    yearEnd: 1980,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -34.0856,
    longitude: -70.3756,
    region: "O'Higgins",
    comuna: 'Machalí',
    featured: true,
    sources: [MC('sewell', 'Campamento minero Sewell')],
  },
  {
    slug: 'el-teniente-1905',
    title: 'Mina El Teniente',
    shortDesc: 'La mina subterránea de cobre más grande del mundo, en operación desde 1905.',
    longDesc:
      'La mina El Teniente fue iniciada por la Braden Copper Company en 1905. Cuenta con más de 4.500 km de túneles, lo que la hace la mina subterránea más grande del mundo. Nacionalizada en 1971 con el cobre, hoy pertenece a Codelco. Produce ~430.000 toneladas anuales de cobre, ~10% de la producción chilena.',
    yearStart: 1905,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -34.0875,
    longitude: -70.3597,
    region: "O'Higgins",
    comuna: 'Machalí',
    sources: [MC('el-teniente', 'Mina El Teniente')],
  },
  {
    slug: 'talca-fundacion-1742',
    title: 'Fundación de Talca',
    shortDesc: 'Talca fue fundada como Villa San Agustín de Talca el 12 de mayo de 1742.',
    longDesc:
      'San Agustín de Talca fue fundada por el gobernador José Antonio Manso de Velasco el 12 de mayo de 1742. Es capital regional del Maule. En su Casa de la Independencia (que aún existe en 1 Norte con 2 Oriente) Bernardo O\'Higgins firmó el Acta de Independencia el 12 de febrero de 1818. Es Monumento Histórico.',
    yearStart: 1742,
    dateText: '12 de mayo de 1742',
    category: 'FUNDACION',
    era: 'COLONIA',
    latitude: -35.4264,
    longitude: -71.6553,
    region: 'Maule',
    comuna: 'Talca',
    sources: [MC('talca', 'Historia de Talca')],
  },
  {
    slug: 'casa-de-la-independencia-talca',
    title: 'Museo O\'Higginiano y Casa de la Independencia',
    shortDesc: 'Casa donde Bernardo O\'Higgins firmó el Acta de Independencia el 12 de febrero de 1818.',
    longDesc:
      'En la calle 1 Norte 875 con 2 Oriente de Talca, está la casa donde Bernardo O\'Higgins, como Director Supremo, firmó el Acta de Independencia de Chile el 12 de febrero de 1818. Construida en 1762, hoy es Museo O\'Higginiano y de Bellas Artes de Talca. Monumento Histórico desde 1971.',
    yearStart: 1762,
    category: 'PATRIMONIO',
    era: 'COLONIA',
    latitude: -35.4297,
    longitude: -71.6622,
    region: 'Maule',
    comuna: 'Talca',
    sources: [CMN('Casa de la Independencia', 1971)],
  },
  {
    slug: 'curico-fundacion-1743',
    title: 'Fundación de Curicó',
    shortDesc: 'Villa San José de la Buena Vista de Curicó, fundada el 9 de octubre de 1743.',
    longDesc:
      'Curicó fue fundada por el gobernador José Antonio Manso de Velasco el 9 de octubre de 1743 como San José de la Buena Vista. Hoy es capital de la provincia homónima de la región del Maule. Centro agroindustrial del valle central, conocido por sus viñas y la Fiesta de la Vendimia. Población actual ~150.000.',
    yearStart: 1743,
    dateText: '9 de octubre de 1743',
    category: 'FUNDACION',
    era: 'COLONIA',
    latitude: -34.9856,
    longitude: -71.2394,
    region: 'Maule',
    comuna: 'Curicó',
    sources: [MC('curico', 'Historia de Curicó')],
  },

  // =========================================================================
  // BIOBÍO / ÑUBLE
  // =========================================================================
  {
    slug: 'concepcion-traslado-1751',
    title: 'Traslado de Concepción al valle de la Mocha',
    shortDesc: 'Tras el maremoto de 1751, Concepción se traslada al actual emplazamiento.',
    longDesc:
      'El maremoto de 1751 destruyó completamente Concepción en su antiguo emplazamiento de Penco. El 24 de noviembre de 1764 se decidió el traslado oficial al valle de la Mocha, su ubicación actual. Es la segunda gran ciudad del país y centro universitario, cultural e industrial del sur centro de Chile.',
    yearStart: 1751,
    yearEnd: 1764,
    category: 'FUNDACION',
    era: 'COLONIA',
    latitude: -36.8267,
    longitude: -73.0497,
    region: 'Biobío',
    comuna: 'Concepción',
    sources: [BN('Historia de Concepción', 'Fernando Campos Harriet', 1979)],
  },
  {
    slug: 'universidad-de-concepcion-1919',
    title: 'Fundación de la Universidad de Concepción',
    shortDesc: 'Primera universidad regional de Chile, fundada el 14 de mayo de 1919.',
    longDesc:
      'La Universidad de Concepción fue fundada el 14 de mayo de 1919 por iniciativa del médico Enrique Molina Garmendia, siendo la tercera universidad de Chile y la primera regional. Su campus de 110 hectáreas con el Foro y la Pinacoteca es uno de los más bellos del país. Su Casa del Arte alberga el mural "Presencia de América Latina" de Jorge González Camarena.',
    yearStart: 1919,
    dateText: '14 de mayo de 1919',
    category: 'CIENCIA',
    era: 'PARLAMENTARISMO',
    latitude: -36.8281,
    longitude: -73.034,
    region: 'Biobío',
    comuna: 'Concepción',
    sources: [MC('udec', 'Universidad de Concepción')],
  },
  {
    slug: 'huachipato-1950',
    title: 'Siderúrgica Huachipato',
    shortDesc: 'CAP inaugura en 1950 la primera siderúrgica integrada de Chile.',
    longDesc:
      'La Compañía de Acero del Pacífico (CAP), filial de CORFO, inauguró en Huachipato (Talcahuano) la primera siderúrgica integrada de Chile el 25 de noviembre de 1950. Produjo el primer acero chileno. Símbolo del proyecto industrializador del Estado emprendedor. Hoy sigue operando bajo el grupo CAP, aunque enfrentando competencia internacional.',
    yearStart: 1950,
    dateText: '25 de noviembre de 1950',
    category: 'ECONOMIA',
    era: 'PRESIDENCIALISMO',
    latitude: -36.7406,
    longitude: -73.1175,
    region: 'Biobío',
    comuna: 'Talcahuano',
    sources: [MC('huachipato', 'Compañía de Acero del Pacífico')],
  },
  {
    slug: 'chillan-fundacion-1580',
    title: 'Fundación de Chillán',
    shortDesc: 'San Bartolomé de Chillán fue fundada por Martín Ruiz de Gamboa el 26 de junio de 1580.',
    longDesc:
      'San Bartolomé de Chillán fue fundada por Martín Ruiz de Gamboa el 26 de junio de 1580 como puesto militar contra los mapuches. Destruida y refundada varias veces. La actual ubicación data de 1835 tras el terremoto. Cuna de Bernardo O\'Higgins (1778) y Arturo Prat (1848). Centro de las "longanizas de Chillán" y la cerámica de Quinchamalí.',
    yearStart: 1580,
    dateText: '26 de junio de 1580',
    category: 'FUNDACION',
    era: 'CONQUISTA',
    latitude: -36.6063,
    longitude: -72.1033,
    region: 'Ñuble',
    comuna: 'Chillán',
    sources: [MC('chillan', 'Historia de Chillán')],
  },
  {
    slug: 'terremoto-chillan-1939',
    title: 'Terremoto de Chillán de 1939',
    shortDesc: 'El 24 de enero de 1939 un terremoto de magnitud 7.8 destruye Chillán y mata 30.000 personas.',
    longDesc:
      'A las 23:32 del 24 de enero de 1939, un terremoto de magnitud 7.8 destruyó las ciudades de Chillán y Concepción. Murieron aproximadamente 30.000 personas, el sismo más mortífero de la historia chilena. La catástrofe llevó a la creación de la CORFO (1939) por Pedro Aguirre Cerda como respuesta del Estado para la reconstrucción y la industrialización.',
    yearStart: 1939,
    dateText: '24 de enero de 1939',
    category: 'DESASTRE_NATURAL',
    era: 'PRESIDENCIALISMO',
    latitude: -36.6066,
    longitude: -72.1033,
    region: 'Ñuble',
    comuna: 'Chillán',
    featured: true,
    sources: [MC('terremoto-1939', 'Terremoto de Chillán')],
  },

  // =========================================================================
  // LA ARAUCANÍA / LOS RÍOS / LOS LAGOS
  // =========================================================================
  {
    slug: 'temuco-fundacion-1881',
    title: 'Fundación de Temuco',
    shortDesc: 'Temuco fue fundada el 24 de febrero de 1881 como fuerte militar en la Pacificación.',
    longDesc:
      'Temuco fue fundada el 24 de febrero de 1881 como fuerte militar durante la Pacificación de la Araucanía. Pablo Neruda creció aquí entre 1906 y 1920. Es la principal ciudad del sur centro de Chile y capital regional. El Mercado Municipal (1929) y el Cerro Ñielol son sus hitos. Centro de la cultura mapuche urbana.',
    yearStart: 1881,
    dateText: '24 de febrero de 1881',
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -38.7359,
    longitude: -72.5904,
    region: 'La Araucanía',
    comuna: 'Temuco',
    sources: [MC('temuco', 'Historia de Temuco')],
  },
  {
    slug: 'valdivia-fundacion-1552',
    title: 'Fundación de Valdivia',
    shortDesc: 'Pedro de Valdivia funda la ciudad de Santa María la Blanca de Valdivia el 9 de febrero de 1552.',
    longDesc:
      'Pedro de Valdivia funda la ciudad de Santa María la Blanca de Valdivia el 9 de febrero de 1552 a orillas del río Calle Calle. Destruida por los mapuches en 1599, fue refundada en 1645 como plaza fuerte fortificada por los españoles para defenderse de corsarios neerlandeses. Centro de la inmigración alemana del XIX. Su universidad (1954) es referente regional.',
    yearStart: 1552,
    dateText: '9 de febrero de 1552',
    category: 'FUNDACION',
    era: 'CONQUISTA',
    latitude: -39.8142,
    longitude: -73.245,
    region: 'Los Ríos',
    comuna: 'Valdivia',
    sources: [BN('Historia de Valdivia', 'Gabriel Guarda', 1953)],
  },
  {
    slug: 'fuertes-valdivia-1645',
    title: 'Sistema de fuertes españoles de Valdivia',
    shortDesc: 'Conjunto de fuertes coloniales construidos desde 1645 para defender el Pacífico.',
    longDesc:
      'Tras la captura neerlandesa de 1643, los españoles construyeron desde 1645 un sistema de fuertes en la desembocadura del Calle Calle: Niebla, Corral, Mancera, Amargos, San Carlos. Era el segundo sistema defensivo más complejo de Sudamérica (tras Cartagena de Indias). Fueron tomados por Lord Cochrane y los patriotas chilenos en 1820. Hoy son Monumento Nacional.',
    yearStart: 1645,
    category: 'BATALLA',
    era: 'COLONIA',
    latitude: -39.8717,
    longitude: -73.4031,
    region: 'Los Ríos',
    comuna: 'Corral',
    sources: [BN('Los fuertes de Valdivia', 'Gabriel Guarda', 1973)],
  },
  {
    slug: 'terremoto-valdivia-1960',
    title: 'Gran Terremoto de Valdivia',
    shortDesc: 'El terremoto más grande registrado en la historia (Mw 9.5) el 22 de mayo de 1960.',
    longDesc:
      'A las 15:11 del 22 de mayo de 1960, un terremoto de magnitud Mw 9.5 sacudió la zona sur de Chile. Es el sismo más grande jamás registrado por instrumentos. El tsunami generado afectó a Hawái, Japón, Filipinas y la costa oeste de EE.UU. Murieron 1.655 personas en Chile y unas 100 más en otros países. Cambió permanentemente la geografía sur (hundimientos de 2 metros).',
    yearStart: 1960,
    dateText: '22 de mayo de 1960',
    category: 'DESASTRE_NATURAL',
    era: 'PRESIDENCIALISMO',
    latitude: -39.8142,
    longitude: -73.245,
    region: 'Los Ríos',
    comuna: 'Valdivia',
    featured: true,
    sources: [MC('terremoto-1960', 'Terremoto de Valdivia, 1960')],
  },
  {
    slug: 'puerto-montt-fundacion-1853',
    title: 'Fundación de Puerto Montt',
    shortDesc: 'Vicente Pérez Rosales funda Melipulli (Puerto Montt) el 12 de febrero de 1853.',
    longDesc:
      'Vicente Pérez Rosales funda Melipulli el 12 de febrero de 1853, renombrada Puerto Montt en 1858. Fue el corazón de la colonización alemana del sur de Chile, llegada a partir de 1851. Capital de Los Lagos, puerto principal del sur austral, entrada a Chiloé y la Patagonia.',
    yearStart: 1853,
    dateText: '12 de febrero de 1853',
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -41.4717,
    longitude: -72.9389,
    region: 'Los Lagos',
    comuna: 'Puerto Montt',
    sources: [BN('Recuerdos del pasado', 'Vicente Pérez Rosales', 1882)],
  },
  {
    slug: 'puerto-varas-1854',
    title: 'Fundación de Puerto Varas',
    shortDesc: 'Colonia alemana fundada en 1854 a orillas del lago Llanquihue.',
    longDesc:
      'Puerto Varas se fundó el 27 de noviembre de 1854 como colonia alemana, llamada así por Antonio Varas, ministro de Manuel Montt y promotor de la colonización. Sus casas estilo bávaro, su Iglesia Sagrado Corazón de Jesús (1918) y la vista al volcán Osorno la convierten en una de las ciudades más turísticas del sur.',
    yearStart: 1854,
    dateText: '27 de noviembre de 1854',
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -41.3192,
    longitude: -72.985,
    region: 'Los Lagos',
    comuna: 'Puerto Varas',
    sources: [MC('puerto-varas', 'Historia de Puerto Varas')],
  },
  {
    slug: 'iglesia-castro-1906',
    title: 'Iglesia San Francisco de Castro',
    shortDesc: 'Construida entre 1906 y 1912, principal iglesia chilota Patrimonio Mundial.',
    longDesc:
      'La Iglesia San Francisco de Castro fue construida entre 1906 y 1912 por el arquitecto italiano Eduardo Provasoli. Su torre de 42 m la hace la más alta de las iglesias chilotas. Su madera pintada de amarillo y morado es ícono visual de Chiloé. Es parte del conjunto Patrimonio de la Humanidad (2000). Monumento Histórico desde 1979.',
    yearStart: 1912,
    category: 'RELIGION',
    era: 'PARLAMENTARISMO',
    latitude: -42.4825,
    longitude: -73.7625,
    region: 'Los Lagos',
    comuna: 'Castro',
    sources: [CMN('Iglesia de Castro', 1979)],
  },

  // =========================================================================
  // AYSÉN / MAGALLANES
  // =========================================================================
  {
    slug: 'coyhaique-fundacion-1929',
    title: 'Fundación de Coyhaique',
    shortDesc: 'Coyhaique fue fundada el 12 de octubre de 1929, capital de Aysén.',
    longDesc:
      'Coyhaique fue fundada el 12 de octubre de 1929 como Baquedano en el cruce del Simpson y el Coyhaique. Renombrada Coyhaique en 1934. Era zona ovejera y maderera. Hoy es la capital de la región de Aysén, puerta a la Patagonia chilena y la Carretera Austral. Población actual ~60.000.',
    yearStart: 1929,
    dateText: '12 de octubre de 1929',
    category: 'FUNDACION',
    era: 'PARLAMENTARISMO',
    latitude: -45.5712,
    longitude: -72.0681,
    region: 'Aysén',
    comuna: 'Coyhaique',
    sources: [MC('coyhaique', 'Historia de Coyhaique')],
  },
  {
    slug: 'carretera-austral-1976',
    title: 'Inicio de la Carretera Austral',
    shortDesc: 'Iniciada en 1976, conecta Puerto Montt con Villa O\'Higgins en 1240 km.',
    longDesc:
      'La Carretera Austral (Ruta 7) fue iniciada en 1976 durante la dictadura como obra estratégica para conectar el aislado sur austral. Tiene 1.240 km entre Puerto Montt y Villa O\'Higgins, atravesando bosques, glaciares y fiordos. Aún tiene tramos sin pavimentar. Es una de las rutas escénicas más espectaculares del mundo.',
    yearStart: 1976,
    category: 'TRANSPORTE',
    era: 'DICTADURA',
    latitude: -44.0667,
    longitude: -72.6833,
    region: 'Aysén',
    comuna: 'Puerto Aysén',
    sources: [MC('carretera-austral', 'Carretera Austral')],
  },
  {
    slug: 'punta-arenas-fundacion-1848',
    title: 'Fundación moderna de Punta Arenas',
    shortDesc: 'Punta Arenas se constituye en 1848, tras trasladarse desde Fuerte Bulnes.',
    longDesc:
      'Tras las difíciles condiciones en Fuerte Bulnes (1843), el gobernador José de los Santos Mardones traslada la colonia chilena al actual sitio de Punta Arenas en 1848. Centro del auge ganadero y comercial del Estrecho de Magallanes. Su riqueza se evidencia en mansiones como el Palacio Sara Braun (1895). Es la ciudad más austral continental del mundo con más de 100.000 habitantes.',
    yearStart: 1848,
    category: 'FUNDACION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -53.1631,
    longitude: -70.9089,
    region: 'Magallanes',
    comuna: 'Punta Arenas',
    sources: [BN('Historia de Magallanes', 'Mateo Martinic', 1992)],
  },
  {
    slug: 'palacio-sara-braun-1895',
    title: 'Palacio Sara Braun',
    shortDesc: 'Mansión más opulenta del sur de Chile, construida en 1895 por la magnate del ganado.',
    longDesc:
      'El Palacio Sara Braun, en Plaza Muñoz Gamero de Punta Arenas, fue construido entre 1895 y 1905 para la magnate Sara Braun, viuda de José Nogueira. Diseño del francés Numa Mayer con materiales importados de Europa. Tras la muerte de Sara (1955), la mansión pasó al Club de la Unión. Es Monumento Histórico desde 1980.',
    yearStart: 1895,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -53.1622,
    longitude: -70.9056,
    region: 'Magallanes',
    comuna: 'Punta Arenas',
    sources: [CMN('Palacio Sara Braun', 1980)],
  },
  {
    slug: 'torres-del-paine-pn-1959',
    title: 'Parque Nacional Torres del Paine',
    shortDesc: 'Parque Nacional creado en 1959, ícono natural de Chile.',
    longDesc:
      'El Parque Nacional Torres del Paine fue creado el 13 de mayo de 1959 como Parque Nacional de Turismo Lago Grey, ampliado en 1961. Sus tres torres de granito (2.500-2.850 msnm), sus glaciares y guanacos lo convirtieron en uno de los parques más visitados del mundo. Es Reserva de la Biosfera (1978) y fue elegida Octava Maravilla del Mundo (2013). Recibe 300.000 visitantes al año.',
    yearStart: 1959,
    dateText: '13 de mayo de 1959',
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -50.9423,
    longitude: -73.4068,
    region: 'Magallanes',
    comuna: 'Torres del Paine',
    featured: true,
    sources: [MC('torres-paine', 'Parque Nacional Torres del Paine')],
  },
  {
    slug: 'puerto-natales-1911',
    title: 'Fundación de Puerto Natales',
    shortDesc: 'Puerto Natales fue fundado el 31 de mayo de 1911 a orillas del Seno Última Esperanza.',
    longDesc:
      'Puerto Natales fue fundado el 31 de mayo de 1911 como puerto para la actividad ganadera ovejera y los frigoríficos. El "Frigorífico Bories" (1915, hoy hotel patrimonial) era el más grande de Sudamérica. Es la puerta a Torres del Paine y al Parque Nacional Bernardo O\'Higgins.',
    yearStart: 1911,
    dateText: '31 de mayo de 1911',
    category: 'FUNDACION',
    era: 'PARLAMENTARISMO',
    latitude: -51.7236,
    longitude: -72.5069,
    region: 'Magallanes',
    comuna: 'Natales',
    sources: [MC('puerto-natales', 'Historia de Puerto Natales')],
  },
]

export const CHILE_REGIONES_VERSION = '0.1.0'
