import type { SeedEvent } from '../types'

/**
 * Sitios físicos georreferenciados de Santiago.
 *
 * Enfoque: cada entrada apunta a un EDIFICIO, ESQUINA, PLAZA o TERRENO
 * concreto, pensado para que la persona, parada frente al lugar, pueda
 * leer "qué era esto antes" o "qué pasó aquí". Coordenadas precisas
 * cuando es posible.
 *
 * Datos placeholder MVP: validar con curador antes de uso público formal.
 */

const MC = (slug: string, topic: string) => ({
  type: 'MEMORIA_CHILENA' as const,
  title: `Memoria Chilena — ${topic}`,
  url: `https://www.memoriachilena.gob.cl/602/w3-search.html?q=${encodeURIComponent(slug)}`,
  citation: `Memoria Chilena (s.f.). ${topic}. Biblioteca Nacional Digital de Chile.`,
})

const CMN = (topic: string, year?: number) => ({
  type: 'ARCHIVO_NACIONAL' as const,
  title: `Consejo de Monumentos Nacionales — ${topic}`,
  citation: `Consejo de Monumentos Nacionales${year ? ` (${year})` : ''}. ${topic}. Ministerio de las Culturas.`,
  inPublicDomain: true,
})

const BN = (title: string, author: string, year: number, signature?: string) => ({
  type: 'BIBLIOTECA_NACIONAL' as const,
  title,
  author,
  year,
  ...(signature ? { signature } : {}),
  citation: `${author} (${year}). ${title}. Biblioteca Nacional de Chile${signature ? `, ${signature}` : ''}.`,
  inPublicDomain: year < 1925,
})

export const SANTIAGO_SITIOS: SeedEvent[] = [
  // =========================================================================
  // CENTRO HISTÓRICO – Plaza de Armas y alrededores
  // =========================================================================
  {
    slug: 'sitio-correo-central',
    title: 'Edificio del Correo Central',
    shortDesc: 'Construido en 1882 sobre el solar del Palacio de los Gobernadores coloniales.',
    longDesc:
      'El Edificio del Correo Central, en el costado norte de la Plaza de Armas, ocupa el lugar donde estuvo el Palacio de los Gobernadores durante toda la Colonia, residencia de Pedro de Valdivia y todos los gobernadores españoles. Construido entre 1881 y 1908 sobre los muros parcialmente subsistentes, es obra de Ricardo Brown. Su tercer piso y mansardas son de Ramón Feherman (1908). Es Monumento Histórico desde 1976.',
    yearStart: 1882,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4369,
    longitude: -70.6504,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Edificio del Correo Central', 1976)],
  },
  {
    slug: 'sitio-municipalidad-santiago',
    title: 'Municipalidad de Santiago (ex Cabildo)',
    shortDesc: 'En este edificio funcionó el Cabildo colonial; hoy es la Municipalidad de Santiago.',
    longDesc:
      'El edificio que hoy alberga la Municipalidad de Santiago, en Plaza de Armas costado norte, fue durante toda la Colonia la sede del Cabildo y la cárcel pública. Construido en 1785 sobre planos de Joaquín Toesca. Fue ampliado en el siglo XIX. Allí se firmó la independencia de la Real Audiencia (1810) y funcionaron por años el Tribunal y la Cárcel.',
    yearStart: 1785,
    category: 'PATRIMONIO',
    era: 'COLONIA',
    latitude: -33.4373,
    longitude: -70.6505,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Joaquín Toesca, arquitecto', 'Pereira Salas', 1965)],
  },
  {
    slug: 'sitio-museo-historico-nacional',
    title: 'Museo Histórico Nacional (ex Real Audiencia)',
    shortDesc: 'Sede de la Real Audiencia colonial; desde 1982 es el Museo Histórico Nacional.',
    longDesc:
      'Este edificio en el costado norte de la Plaza de Armas (Plaza de Armas 951) fue construido entre 1804 y 1808 para albergar la Real Audiencia y la Cancillería del Reino de Chile. Tras la independencia fue Tesoro Nacional y luego Casa de Moneda hasta 1929. Desde 1982 es el Museo Histórico Nacional, con colecciones desde el período prehispánico hasta la dictadura.',
    yearStart: 1808,
    category: 'PATRIMONIO',
    era: 'COLONIA',
    latitude: -33.437,
    longitude: -70.6498,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('mhn', 'Museo Histórico Nacional')],
  },
  {
    slug: 'sitio-iglesia-merced',
    title: 'Basílica de la Merced',
    shortDesc: 'Templo mercedario erigido en 1735 en el lugar de una iglesia anterior de 1546.',
    longDesc:
      'La Basílica de la Merced, en Mac Iver 341 esquina Merced, es uno de los templos más antiguos de Santiago. Su primera versión data de 1546, fundada por Antonio Correa. La actual edificación se completa en 1795 con dos torres barrocas. Custodia la Virgen de la Merced, una de las patronas de Santiago, y una imagen del Cristo Crucificado del siglo XVII.',
    yearStart: 1735,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -33.4382,
    longitude: -70.6482,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Iglesias coloniales de Santiago', 'Pereira Salas', 1965)],
  },
  {
    slug: 'sitio-pasaje-matte',
    title: 'Pasaje Matte',
    shortDesc: 'Pasaje comercial de 1869, primer pasaje cubierto de Santiago.',
    longDesc:
      'Inaugurado en 1869, el Pasaje Matte une Ahumada con Estado, entre Huérfanos y Compañía. Fue el primer pasaje cubierto de Santiago, inspirado en los pasajes parisinos. Su techumbre de fierro y vidrio fue una novedad arquitectónica. Albergó cafés, librerías y locales de moda. Aún funciona como galería comercial. Es Monumento Histórico.',
    yearStart: 1869,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4393,
    longitude: -70.6502,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('pasaje-matte', 'Pasajes comerciales de Santiago')],
  },
  {
    slug: 'sitio-pasaje-philips',
    title: 'Pasaje Phillips',
    shortDesc: 'Pasaje peatonal entre Plaza de Armas y Puente, antiguo callejón colonial.',
    longDesc:
      'El Pasaje Phillips une la Plaza de Armas con la calle Puente. Su trazado es colonial y conserva fachadas del siglo XIX. Fue históricamente un eje comercial de menudeo. Con la peatonalización del centro en los años 70, recuperó protagonismo y hoy es uno de los pasajes más transitados.',
    yearStart: 1870,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4373,
    longitude: -70.651,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('pasaje-phillips', 'Pasaje Phillips')],
  },
  {
    slug: 'sitio-edificio-comercial-edwards',
    title: 'Edificio Edwards en la Alameda',
    shortDesc: 'Sede del Banco Edwards desde 1920 en la esquina de Bandera.',
    longDesc:
      'Construido entre 1916 y 1920 por el arquitecto Alberto Cruz Montt, el Edificio Edwards en la esquina de la Alameda con Bandera fue por décadas la casa matriz del Banco Edwards. Su estilo neorrenacentista con fachadas de granito lo hicieron símbolo del sector financiero. Hoy alberga oficinas tras varias intervenciones.',
    yearStart: 1920,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4421,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('edwards', 'Banco Edwards')],
  },
  {
    slug: 'sitio-club-santiago',
    title: 'Edificio del antiguo Club Santiago',
    shortDesc: 'Mansión de 1894 en calle Catedral, hoy oficinas y sede de actos públicos.',
    longDesc:
      'En la calle Catedral con Bandera, el antiguo Club Santiago se construyó en 1894 como sede social masculina. Su salón principal albergó por décadas tertulias políticas y bailes. Tras el cierre del club, el edificio pasó a ser sede de instituciones culturales y oficinas. Es uno de los pocos ejemplos sobrevivientes de mansión social del centro.',
    yearStart: 1894,
    category: 'CULTURA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4381,
    longitude: -70.6533,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('club-santiago', 'Clubes sociales de Santiago')],
  },
  {
    slug: 'sitio-edificio-ariztia',
    title: 'Edificio Ariztía',
    shortDesc: 'Primer rascacielos de Chile (12 pisos) en la Alameda con Nueva York, 1921.',
    longDesc:
      'Construido entre 1917 y 1921 por encargo del agricultor Rafael Ariztía, este edificio de 12 pisos fue considerado el primer rascacielos de Sudamérica. Su autor fue Alberto Cruz Montt. Estructura de acero y hormigón armado, fachada neoclásica, con uno de los primeros ascensores eléctricos del país. Está en Nueva York 33. Es Monumento Nacional desde 2008.',
    yearStart: 1921,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4427,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Edificio Ariztía', 2008)],
  },
  {
    slug: 'sitio-bolsa-comercio',
    title: 'Edificio de la Bolsa de Comercio',
    shortDesc: 'Construido en 1917 en La Bolsa con Nueva York, símbolo del barrio financiero clásico.',
    longDesc:
      'Diseñado por Emile Jecquier en estilo Beaux-Arts, el edificio de la Bolsa de Comercio se inauguró en 1917. Está en La Bolsa 64, frente al Club de la Unión. Su rotonda central con cúpula vidriada es uno de los espacios más fotografiados de Santiago. Aún funciona como sede de la Bolsa de Comercio. Es Monumento Histórico desde 1981.',
    yearStart: 1917,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4434,
    longitude: -70.652,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Edificio Bolsa de Comercio', 1981)],
  },
  {
    slug: 'sitio-ex-congreso-nacional',
    title: 'Edificio del ex Congreso Nacional',
    shortDesc: 'Sede del Congreso entre 1876 y 1973; hoy de la Cancillería.',
    longDesc:
      'El edificio del ex Congreso Nacional, en Catedral con Bandera, ocupa el solar de la antigua Iglesia de la Compañía, destruida en el incendio de 1863. Construido entre 1858 y 1876 en estilo neoclásico francés (arquitectos Lucien Hénault y Manuel Aldunate), albergó al Congreso hasta el golpe de 1973. Tras 1990, el Congreso se trasladó a Valparaíso. Hoy alberga al Ministerio de Relaciones Exteriores.',
    yearStart: 1876,
    category: 'POLITICA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4378,
    longitude: -70.6531,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Historia del Congreso Nacional', 'Domingo Amunátegui', 1925)],
  },
  {
    slug: 'sitio-tribunales-justicia',
    title: 'Palacio de Tribunales de Justicia',
    shortDesc: 'Sede de la Corte Suprema desde 1930 en plaza Montt-Varas.',
    longDesc:
      'El Palacio de los Tribunales de Justicia fue diseñado por Emilio Doyère y construido entre 1907 y 1930. Su fachada neoclásica con seis columnas corintias enfrenta la plaza Montt-Varas (Compañía con Morandé). Alberga la Corte Suprema, las Cortes de Apelaciones y el Pleno. Es uno de los íconos institucionales de Santiago. Monumento Histórico desde 1981.',
    yearStart: 1930,
    category: 'POLITICA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4391,
    longitude: -70.6531,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Palacio de Tribunales', 1981)],
  },
  {
    slug: 'sitio-galeria-paris',
    title: 'Galería París en pleno centro',
    shortDesc: 'Galería comercial de 1925, ícono comercial del Santiago de entreguerras.',
    longDesc:
      'Inaugurada en 1925 sobre la Alameda, la Galería París conectó la calle Estado con Bandera. Su techo de cristal y locales de moda francesa la convirtieron en referente del consumo elegante. Sufrió daños en el incendio de 1991 pero fue restaurada. Ya no conserva el comercio histórico pero sí la arquitectura.',
    yearStart: 1925,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4424,
    longitude: -70.6503,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('galeria-paris', 'Galerías comerciales de Santiago')],
  },
  {
    slug: 'sitio-iglesia-agustinas',
    title: 'Monasterio de las Agustinas',
    shortDesc: 'Monasterio fundado en 1574, una de las congregaciones femeninas más antiguas del país.',
    longDesc:
      'El Monasterio de las Agustinas fue fundado en 1574 y le da nombre a la calle Agustinas. Su iglesia conserva piezas del XVII y XVIII pese a las reconstrucciones por terremotos. Fue uno de los principales conventos coloniales de monjas. Aún funciona como monasterio activo. La iglesia abre al público en festividades.',
    yearStart: 1574,
    category: 'RELIGION',
    era: 'CONQUISTA',
    latitude: -33.4395,
    longitude: -70.6504,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Monasterios femeninos de Santiago', 'René Salinas Meza', 1985)],
  },
  {
    slug: 'sitio-ex-banco-edwards-bandera',
    title: 'Antigua sede del Banco Edwards',
    shortDesc: 'Edificio de 1893 en Bandera, primera sede del Banco Edwards.',
    longDesc:
      'En el cruce de Bandera con Compañía, el primer edificio del Banco Edwards data de 1893. Diseñado en estilo neorrenacentista, fue una de las primeras casas matrices bancarias del centro. Tras el traslado del banco al edificio nuevo en 1920, pasó a oficinas. Conserva fachada original.',
    yearStart: 1893,
    category: 'ECONOMIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4391,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('banca-historica', 'Bancos históricos de Chile')],
  },

  // =========================================================================
  // ALAMEDA Y BARRIO UNIVERSITARIO
  // =========================================================================
  {
    slug: 'sitio-casa-central-uchile',
    title: 'Casa Central de la Universidad de Chile',
    shortDesc: 'Inaugurada en 1872 como sede principal de la Universidad de Chile.',
    longDesc:
      'La Casa Central de la Universidad de Chile, en la Alameda con calle Arturo Prat, fue inaugurada en 1872 sobre los terrenos del Convento Grande de San Francisco. Su autor fue el arquitecto francés Lucien Hénault. Estilo neoclásico con frontón triangular y columnata. Es la sede del rector y oficinas centrales. Monumento Histórico desde 1974.',
    yearStart: 1872,
    category: 'CIENCIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4434,
    longitude: -70.6493,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Casa Central UChile', 1974)],
  },
  {
    slug: 'sitio-casa-central-uc',
    title: 'Casa Central de la Universidad Católica',
    shortDesc: 'Sede inaugurada en 1910 frente a la Alameda con avenida Vicuña Mackenna.',
    longDesc:
      'La Casa Central de la Pontificia Universidad Católica fue inaugurada en 1910 con motivo del Centenario, en Alameda 340. Diseño de Ignacio Cremonesi en estilo italianizante. Sus fachadas en piedra rosa y patios interiores con galerías son parte del paisaje urbano. Alberga rectoría, salas de clase y la Iglesia de la Anunciación. Monumento Nacional.',
    yearStart: 1910,
    category: 'CIENCIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4414,
    longitude: -70.6378,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Casa Central UC', 1981)],
  },
  {
    slug: 'sitio-instituto-nacional',
    title: 'Instituto Nacional General José Miguel Carrera',
    shortDesc: 'Liceo emblemático fundado en 1813, una de las cunas de la elite intelectual chilena.',
    longDesc:
      'El Instituto Nacional fue fundado el 10 de agosto de 1813 por iniciativa de la Junta de Gobierno. Su sede actual en Arturo Prat con Alameda data de 1850. Por sus aulas pasaron 17 presidentes de Chile, entre ellos Manuel Bulnes, Domingo Santa María, Pedro Montt, Eduardo Frei, Salvador Allende y Ricardo Lagos. Es Monumento Histórico.',
    yearStart: 1813,
    category: 'CIENCIA',
    era: 'INDEPENDENCIA',
    latitude: -33.4435,
    longitude: -70.6488,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Historia del Instituto Nacional', 'Domingo Amunátegui', 1889)],
  },
  {
    slug: 'sitio-iglesia-san-isidro-labrador',
    title: 'Iglesia de San Isidro Labrador',
    shortDesc: 'Templo erigido en 1735 en San Isidro 525, antiguo barrio rural de Santiago.',
    longDesc:
      'La Iglesia de San Isidro Labrador, en San Isidro con Eyzaguirre, data de 1735 y es uno de los pocos ejemplos de iglesia de adobe colonial sobreviviente en el centro. Le da nombre al barrio que originalmente era rural. Es Monumento Histórico desde 1973.',
    yearStart: 1735,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -33.4495,
    longitude: -70.6435,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Iglesia San Isidro', 1973)],
  },
  {
    slug: 'sitio-cerveceria-andres-ebner',
    title: 'Antigua Cervecería Andrés Ebner',
    shortDesc: 'Fábrica de cerveza fundada en 1872 por inmigrantes alemanes en Independencia.',
    longDesc:
      'La Cervecería Andrés Ebner, fundada en 1872 por inmigrantes alemanes en el barrio Independencia, fue una de las primeras industrias cerveceras del país. En 1916 fue absorbida por la Compañía Cervecerías Unidas (CCU), formando el actual conglomerado. El edificio original fue parcialmente demolido pero subsisten algunas dependencias.',
    yearStart: 1872,
    category: 'ECONOMIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4214,
    longitude: -70.6527,
    region: 'Metropolitana',
    comuna: 'Independencia',
    sources: [MC('ccu', 'Cervecerías Unidas (CCU)')],
  },
  {
    slug: 'sitio-cite-bandera',
    title: 'Cités históricos de la calle Bandera',
    shortDesc: 'Conjunto de cités obreros del temprano siglo XX en el barrio Brasil.',
    longDesc:
      'Los cités —pequeños conjuntos de viviendas obreras alrededor de un patio común— fueron tipología característica del Santiago de inicios del siglo XX. La calle Bandera entre Catedral y Compañía conserva varios. Eran respuesta a la migración campo-ciudad. Hoy varios son zonas típicas y se restauran como vivienda asequible.',
    yearStart: 1910,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4366,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('cites', 'Cités y conventillos de Santiago')],
  },

  // =========================================================================
  // BARRIO LASTARRIA / FORESTAL
  // =========================================================================
  {
    slug: 'sitio-iglesia-vera-cruz',
    title: 'Iglesia de la Vera Cruz',
    shortDesc: 'Templo construido en 1857 en el barrio Lastarria, uno de los más bellos del centro.',
    longDesc:
      'La Iglesia de la Vera Cruz fue erigida en 1857 frente al actual barrio Lastarria, sobre el solar de una antigua ermita. Está en José Victorino Lastarria 124. Su estilo neogótico, con torres asimétricas y vitrales franceses, la hicieron singular. Su orden franciscano la administró hasta 1949. Hoy depende del Arzobispado. Monumento Histórico.',
    yearStart: 1857,
    category: 'RELIGION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4382,
    longitude: -70.6427,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Iglesia Vera Cruz', 1976)],
  },
  {
    slug: 'sitio-plaza-mulato-gil',
    title: 'Plaza Mulato Gil de Castro',
    shortDesc: 'Plaza interior del barrio Lastarria con galerías de arte y cafés.',
    longDesc:
      'La Plaza Mulato Gil de Castro, en pleno barrio Lastarria, debe su nombre al pintor mulato peruano que retrató a las elites independentistas chilenas. Está en Lastarria 305-307. Es una plaza interior bordeada por la Casa José Victorino Lastarria, el Museo Arqueológico de Santiago y galerías de arte. Punto de encuentro bohemio desde los años 80.',
    yearStart: 1980,
    category: 'CULTURA',
    era: 'DICTADURA',
    latitude: -33.4384,
    longitude: -70.6418,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('mulato-gil', 'Plaza Mulato Gil de Castro')],
  },
  {
    slug: 'sitio-casa-jose-victorino-lastarria',
    title: 'Casa José Victorino Lastarria',
    shortDesc: 'Mansión de 1845 que pertenece al jurista y escritor José Victorino Lastarria.',
    longDesc:
      'La casa de José Victorino Lastarria, en la calle que lleva su nombre, data de 1845. El intelectual liberal —fundador de la Academia de Bellas Letras y figura del liberalismo del XIX— vivió aquí desde 1858. Hoy es sede de la Sociedad Chilena de Historia y Geografía. Conserva mobiliario original.',
    yearStart: 1845,
    category: 'CULTURA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4385,
    longitude: -70.6408,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Recuerdos literarios', 'José Victorino Lastarria', 1878)],
  },
  {
    slug: 'sitio-edificio-merced-738',
    title: 'Edificio Merced 738 (Casa Bruna)',
    shortDesc: 'Mansión de 1902 reconvertida en hotel boutique.',
    longDesc:
      'En la calle Merced 738, en el límite entre el centro y Lastarria, se levanta una mansión de 1902 conocida popularmente como "Casa Bruna" por su última propietaria. De estilo afrancesado, con dos pisos y mansardas, fue residencia de familias acomodadas hasta los 60. Recientemente fue restaurada como hotel boutique conservando su fachada y patios.',
    yearStart: 1902,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4378,
    longitude: -70.6406,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('merced-738', 'Patrimonio del barrio Lastarria')],
  },
  {
    slug: 'sitio-edificio-foresta',
    title: 'Edificio Foresta',
    shortDesc: 'Edificio art decó de 1929 frente al Parque Forestal.',
    longDesc:
      'El Edificio Foresta, en Cardenal Caro frente al Parque Forestal, se construyó en 1929 en estilo art decó. Diseñado por Larraín y Prieto Vial, tiene 14 pisos y fue uno de los primeros edificios de departamentos altos del centro. Vivieron allí Pablo Neruda, Vicente Huidobro y Gabriela Mistral en distintos momentos. Es Monumento Histórico.',
    yearStart: 1929,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4351,
    longitude: -70.6403,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Edificio Foresta', 2005)],
  },
  {
    slug: 'sitio-museo-arte-contemporaneo',
    title: 'Museo de Arte Contemporáneo (MAC)',
    shortDesc: 'Ala oriente del Palacio de Bellas Artes; alberga el MAC desde 1947.',
    longDesc:
      'El Museo de Arte Contemporáneo (MAC) ocupa el ala oriente del Palacio de Bellas Artes desde 1947. Depende de la Universidad de Chile. Su misión es exhibir arte contemporáneo chileno y latinoamericano. Tiene una sede secundaria en Quinta Normal. Sus colecciones incluyen obras de Roberto Matta, Gracia Barrios, Eugenio Dittborn y Alfredo Jaar.',
    yearStart: 1947,
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4357,
    longitude: -70.64,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('mac', 'Museo de Arte Contemporáneo')],
  },

  // =========================================================================
  // BARRIO BRASIL / YUNGAY / DIECIOCHO
  // =========================================================================
  {
    slug: 'sitio-plaza-brasil',
    title: 'Plaza Brasil',
    shortDesc: 'Plaza fundada en 1888 en el corazón del Barrio Brasil.',
    longDesc:
      'La Plaza Brasil fue diseñada por Manuel Aldunate e inaugurada en 1888. Está enmarcada por Huérfanos, Compañía, Cumming y Maturana. Su pileta central de mármol data de 1907. El barrio se desarrolló a fines del XIX como zona residencial de clase media-alta y conserva mansiones afrancesadas. Hoy es Zona Típica y centro bohemio del poniente del centro.',
    yearStart: 1888,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4419,
    longitude: -70.67,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('barrio-brasil', 'Barrio Brasil')],
  },
  {
    slug: 'sitio-iglesia-preciosa-sangre',
    title: 'Iglesia de la Preciosa Sangre',
    shortDesc: 'Templo de 1882 en pleno Barrio Brasil, sede del colegio del mismo nombre.',
    longDesc:
      'Construida en 1882 en estilo neogótico francés por iniciativa de los Padres de la Preciosa Sangre, esta iglesia destaca por su fachada de tres torres y vitrales. Junto al colegio formó por décadas el corazón religioso y educativo del Barrio Brasil. Es Monumento Histórico desde 2009.',
    yearStart: 1882,
    category: 'RELIGION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4434,
    longitude: -70.6691,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Iglesia Preciosa Sangre', 2009)],
  },
  {
    slug: 'sitio-monumento-roto-chileno',
    title: 'Monumento al Roto Chileno (Plaza Yungay)',
    shortDesc: 'Estatua de 1888 que conmemora al combatiente popular en la Batalla de Yungay.',
    longDesc:
      'El Monumento al Roto Chileno se erigió en 1888 en el centro de la Plaza Yungay (intersección de Sotomayor con Portales), conmemorando al soldado anónimo que luchó en la Batalla de Yungay (1839). Su autor fue Virginio Arias. Cada 20 de enero se conmemora "El día del Roto Chileno" con actos en la plaza. Es Monumento Histórico.',
    yearStart: 1888,
    category: 'POLITICA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4392,
    longitude: -70.67,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Monumento al Roto', 1980)],
  },
  {
    slug: 'sitio-fundicion-libertad',
    title: 'Antigua Fundición Libertad',
    shortDesc: 'Fábrica de hierro fundido de 1894 en el Barrio Yungay.',
    longDesc:
      'La Fundición Libertad, en la calle Libertad del Barrio Yungay, fue una de las pocas fundiciones grandes del centro de Santiago. Operó entre 1894 y mediados del XX. Su edificio industrial de ladrillo a la vista subsiste y fue reconvertido en talleres y galpones culturales. Es testigo de la industrialización del Santiago del 900.',
    yearStart: 1894,
    category: 'ECONOMIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4408,
    longitude: -70.6722,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('industrias-yungay', 'Industrias del Barrio Yungay')],
  },
  {
    slug: 'sitio-casa-museo-vicuna-mackenna',
    title: 'Quinta Vergara — Casa Museo Vicuña Mackenna',
    shortDesc: 'Quinta donde vivió Benjamín Vicuña Mackenna entre 1860 y 1886.',
    longDesc:
      'En la calle Vicuña Mackenna 94, la quinta donde vivió el intendente y escritor Benjamín Vicuña Mackenna fue convertida en Museo Casa Vicuña Mackenna. Conserva mobiliario, biblioteca y manuscritos del autor de "Historia crítica y social de Santiago". Es Monumento Histórico.',
    yearStart: 1860,
    yearEnd: 1886,
    category: 'CULTURA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4517,
    longitude: -70.6311,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [BN('Vida de Vicuña Mackenna', 'Ricardo Donoso', 1925)],
  },

  // =========================================================================
  // PARQUE FORESTAL Y RIBERA NORTE DEL MAPOCHO
  // =========================================================================
  {
    slug: 'sitio-puente-cal-y-canto-restos',
    title: 'Restos del Puente Cal y Canto',
    shortDesc: 'Vestigios del puente colonial visibles bajo el Parque de los Reyes.',
    longDesc:
      'Aunque el Puente Cal y Canto fue demolido en 1888, parte de sus cimientos fueron descubiertos durante las obras del Metro. Hoy una placa en la estación Cal y Canto recuerda su trazado. En el Parque de los Reyes, junto al Mapocho, se conservan algunas piedras originales. Era el primer puente firme sobre el río.',
    yearStart: 1782,
    category: 'TRANSPORTE',
    era: 'COLONIA',
    latitude: -33.4347,
    longitude: -70.6499,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('cal-y-canto', 'Puente Cal y Canto')],
  },
  {
    slug: 'sitio-parque-de-los-reyes',
    title: 'Parque de los Reyes',
    shortDesc: 'Parque urbano de 7 hectáreas inaugurado en 1991 sobre la antigua estación de carga.',
    longDesc:
      'El Parque de los Reyes se inauguró en 1991 en los terrenos de la antigua estación de carga ferroviaria del Mapocho. Su nombre honra la visita de los Reyes de España en 1990. Tiene fuentes, monumentos y esculturas. Es uno de los principales parques urbanos del centro y conecta visualmente con el Parque Forestal.',
    yearStart: 1991,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4326,
    longitude: -70.6557,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('parque-reyes', 'Parque de los Reyes')],
  },
  {
    slug: 'sitio-fuente-alemana',
    title: 'Fuente Alemana',
    shortDesc: 'Fuente monumental donada por la colonia alemana en 1910 para el Centenario.',
    longDesc:
      'La Fuente Alemana fue donada por la colectividad alemana de Chile para el Centenario en 1910. Diseñada por Gustav Eberlein, representa a Chile como una mujer joven rodeada por figuras alegóricas. Está en el extremo oriente del Parque Forestal, junto a Plaza Italia. Es Monumento Histórico.',
    yearStart: 1910,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4378,
    longitude: -70.6359,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Fuente Alemana', 1986)],
  },
  {
    slug: 'sitio-monumento-baquedano',
    title: 'Plaza Baquedano (ex Plaza Dignidad)',
    shortDesc: 'Plaza bautizada en 1928 en honor al general Manuel Baquedano.',
    longDesc:
      'La Plaza Baquedano, en el cruce de Alameda con Av. Vicuña Mackenna y Av. Providencia, fue inaugurada en 1928 con la estatua ecuestre del general Manuel Baquedano, héroe de la Guerra del Pacífico. Conocida popularmente como Plaza Italia desde inicios del XX por la cercanía con el barrio italiano. Durante el estallido social de 2019 fue rebautizada por los manifestantes como "Plaza Dignidad". La estatua de Baquedano fue retirada en marzo de 2021.',
    yearStart: 1928,
    category: 'POLITICA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4368,
    longitude: -70.6342,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('baquedano', 'Plaza Baquedano')],
  },

  // =========================================================================
  // PROVIDENCIA
  // =========================================================================
  {
    slug: 'sitio-iglesia-providencia',
    title: 'Iglesia de la Divina Providencia',
    shortDesc: 'Templo de 1853 que da nombre a la comuna.',
    longDesc:
      'La Iglesia de la Divina Providencia fue inaugurada en 1853 cuando Providencia era todavía una zona rural. Le da nombre a la comuna que se desarrolló alrededor. Su estilo neogótico la hace singular. Conserva la imagen original de la Virgen de la Divina Providencia. Es Monumento Histórico.',
    yearStart: 1853,
    category: 'RELIGION',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4319,
    longitude: -70.6267,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [CMN('Iglesia Providencia', 1985)],
  },
  {
    slug: 'sitio-edificio-tajamar',
    title: 'Edificio Tajamar',
    shortDesc: 'Conjunto residencial de 1962 que marcó la modernidad arquitectónica de Providencia.',
    longDesc:
      'El conjunto Tajamar, en avenida Providencia con calle Carlos Antúnez, fue diseñado por BVCH (Bresciani, Valdés, Castillo, Huidobro) e inaugurado en 1962. Compuesto por torres de departamentos y zócalos comerciales en torno a una plaza interior, fue pionero del urbanismo moderno chileno. Hoy es Zona de Conservación Histórica.',
    yearStart: 1962,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4225,
    longitude: -70.6225,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('tajamar', 'Conjunto Tajamar')],
  },
  {
    slug: 'sitio-chacra-valparaiso',
    title: 'Antigua Chacra Valparaíso',
    shortDesc: 'Las actuales calles de Providencia ocupan los terrenos de la chacra de Domingo de Erazo.',
    longDesc:
      'Buena parte de la actual avenida Providencia y sus calles transversales (Pedro de Valdivia, Manuel Montt, Ricardo Lyon) corresponden a la subdivisión de la antigua chacra Valparaíso, propiedad colonial de la familia Erazo. La parcelación se inició a fines del XIX y dio origen a la comuna en 1897. Antes era zona de viñas y huertos.',
    yearStart: 1897,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4264,
    longitude: -70.6166,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('historia-providencia', 'Historia urbana de Providencia')],
  },
  {
    slug: 'sitio-parque-bustamante',
    title: 'Parque Bustamante',
    shortDesc: 'Parque longitudinal sobre el ex Parque Tropical, columna verde de Providencia.',
    longDesc:
      'El Parque Bustamante recorre 800 metros entre la avenida Italia y la Plaza Baquedano. Originalmente fue el "Parque Tropical" en los terrenos del antiguo Cementerio de Disidentes (1854-1875). Reformado varias veces, es el principal eje verde de Providencia. Bajo él pasa la Línea 5 del Metro.',
    yearStart: 1900,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4395,
    longitude: -70.6328,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('bustamante', 'Parque Bustamante')],
  },
  {
    slug: 'sitio-clinica-santa-maria',
    title: 'Clínica Santa María',
    shortDesc: 'Clínica donde murió Pablo Neruda el 23 de septiembre de 1973.',
    longDesc:
      'Inaugurada en 1938, la Clínica Santa María en Providencia es una de las más antiguas del país. Pablo Neruda murió aquí el 23 de septiembre de 1973, oficialmente de cáncer. Investigaciones forenses posteriores (2013, 2016) sugieren posible envenenamiento por la dictadura, sin conclusión definitiva. La habitación 406 es sitio de memoria informal.',
    yearStart: 1938,
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4239,
    longitude: -70.6203,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [BN('Muerte de Neruda', 'Mario Amorós', 2014)],
  },
  {
    slug: 'sitio-edificio-cepal',
    title: 'Edificio CEPAL',
    shortDesc: 'Sede regional de la Comisión Económica para América Latina, inaugurada en 1966.',
    longDesc:
      'El edificio de la CEPAL en avenida Dag Hammarskjöld 3477, Vitacura, es obra del arquitecto Emilio Duhart inaugurada en 1966. Su forma escultórica de hormigón es uno de los íconos del brutalismo chileno. Es Monumento Histórico desde 2010. Sigue siendo sede de la CEPAL.',
    yearStart: 1966,
    category: 'POLITICA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.408,
    longitude: -70.592,
    region: 'Metropolitana',
    comuna: 'Vitacura',
    sources: [CMN('Edificio CEPAL', 2010)],
  },

  // =========================================================================
  // ÑUÑOA / MACUL
  // =========================================================================
  {
    slug: 'sitio-plaza-nunoa',
    title: 'Plaza Ñuñoa',
    shortDesc: 'Plaza fundacional del antiguo pueblo de Ñuñoa, hoy centro comunal.',
    longDesc:
      'La Plaza Ñuñoa marca el sitio del pueblo originario de Ñuñoa, asentamiento prehispánico que dio nombre a la comuna. La iglesia matriz, construida en 1883, fue destruida por el terremoto de 1985 y reemplazada por la actual. La plaza es centro de encuentro nocturno y gastronómico desde los 90.',
    yearStart: 1900,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4566,
    longitude: -70.5972,
    region: 'Metropolitana',
    comuna: 'Ñuñoa',
    sources: [MC('nunoa', 'Historia de Ñuñoa')],
  },
  {
    slug: 'sitio-iglesia-matriz-nunoa',
    title: 'Iglesia Matriz de Ñuñoa',
    shortDesc: 'Iglesia inaugurada en 1990 sobre el sitio de la antigua parroquia destruida en 1985.',
    longDesc:
      'La actual Iglesia Matriz de Ñuñoa fue inaugurada en 1990 tras el colapso de la antigua parroquia (1883) durante el terremoto del 3 de marzo de 1985. Su diseño moderno contrasta con el estilo neoclásico anterior. Conserva imágenes y campanas de la iglesia anterior.',
    yearStart: 1990,
    category: 'RELIGION',
    era: 'TRANSICION',
    latitude: -33.4566,
    longitude: -70.597,
    region: 'Metropolitana',
    comuna: 'Ñuñoa',
    sources: [MC('iglesia-nunoa', 'Iglesia matriz de Ñuñoa')],
  },
  {
    slug: 'sitio-estadio-nacional-coliseo',
    title: 'Coliseo Estadio Nacional',
    shortDesc: 'Recinto multiuso techado del Parque Estadio Nacional.',
    longDesc:
      'El Coliseo del Estadio Nacional, construido en 1976, es un recinto cerrado multiuso para básquet, vóley, eventos masivos y conciertos. Su capacidad es de 8.000 personas. Forma parte del complejo Parque Estadio Nacional. Renovado para los Panamericanos 2023.',
    yearStart: 1976,
    category: 'CULTURA',
    era: 'DICTADURA',
    latitude: -33.4636,
    longitude: -70.6111,
    region: 'Metropolitana',
    comuna: 'Ñuñoa',
    sources: [MC('coliseo-nacional', 'Coliseo Estadio Nacional')],
  },
  {
    slug: 'sitio-velodromo-penalolen',
    title: 'Velódromo de Peñalolén',
    shortDesc: 'Velódromo techado construido para los Panamericanos 2023.',
    longDesc:
      'El Velódromo de Peñalolén fue construido específicamente para los Juegos Panamericanos 2023. Tiene pista de madera de 250 metros y capacidad para 3.000 espectadores. Es la sede del ciclismo de alto rendimiento de Chile. Es uno de los recintos de mayor calidad del país.',
    yearStart: 2023,
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4972,
    longitude: -70.5378,
    region: 'Metropolitana',
    comuna: 'Peñalolén',
    sources: [MC('velodromo', 'Velódromo de Peñalolén')],
  },

  // =========================================================================
  // BARRIO REPÚBLICA / MEIGGS / ESTACIÓN CENTRAL
  // =========================================================================
  {
    slug: 'sitio-palacio-irarrazaval',
    title: 'Palacio Irarrázaval',
    shortDesc: 'Mansión de 1899 en barrio República, hoy sede de oficinas universitarias.',
    longDesc:
      'El Palacio Irarrázaval, en avenida República, fue construido en 1899 para Manuel José Irarrázaval. Diseño afrancesado de Eugenio Joannon. Tras la decadencia residencial del barrio en los 60, fue ocupado por sedes universitarias. Hoy alberga oficinas de la Universidad de las Américas. Monumento Nacional desde 1986.',
    yearStart: 1899,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4503,
    longitude: -70.6603,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Palacio Irarrázaval', 1986)],
  },
  {
    slug: 'sitio-barrio-meiggs',
    title: 'Barrio Meiggs',
    shortDesc: 'Barrio comercial mayorista que ocupa terrenos del antiguo paraje San Borja.',
    longDesc:
      'El Barrio Meiggs, alrededor de la calle homónima en honor al ingeniero Henry Meiggs, es desde mediados del XX el principal centro comercial mayorista de Santiago. Sus calles peatonales acogen miles de tiendas de ropa, juguetes, electrónica. Operan miles de comerciantes muchos de ellos migrantes. Es uno de los barrios más visitados del Santiago popular.',
    yearStart: 1950,
    category: 'ECONOMIA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4524,
    longitude: -70.6745,
    region: 'Metropolitana',
    comuna: 'Estación Central',
    sources: [MC('meiggs', 'Barrio Meiggs')],
  },
  {
    slug: 'sitio-cervantes-instituto-pedagogico',
    title: 'Ex Instituto Pedagógico (Campus Macul)',
    shortDesc: 'Sede tradicional de formación docente fundada en 1889.',
    longDesc:
      'El Instituto Pedagógico de la Universidad de Chile fue fundado en 1889 con maestros alemanes. Su sede en Macul, conocida como Pedagógico, formó a generaciones de profesores chilenos. Fue cuna de movimientos estudiantiles emblemáticos. Pasó a la Universidad Metropolitana de Ciencias de la Educación (UMCE) en 1981.',
    yearStart: 1889,
    category: 'CIENCIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4694,
    longitude: -70.5969,
    region: 'Metropolitana',
    comuna: 'Macul',
    sources: [BN('Historia de la educación en Chile', 'Sol Serrano', 2012)],
  },

  // =========================================================================
  // RECOLETA / INDEPENDENCIA
  // =========================================================================
  {
    slug: 'sitio-hospital-san-jose',
    title: 'Hospital San José',
    shortDesc: 'Hospital fundado en 1872 como lazareto de viruela en La Chimba.',
    longDesc:
      'Inaugurado en 1872 como Hospital de Variolosos (lazareto de viruela), el San José fue extendiendo sus servicios. Su edificio principal de 1929 es Monumento Histórico. Hoy es referente metropolitano de cirugía y trauma. Está en avenida Independencia con Profesor Alberto Zañartu.',
    yearStart: 1872,
    category: 'CIENCIA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4111,
    longitude: -70.6611,
    region: 'Metropolitana',
    comuna: 'Independencia',
    sources: [CMN('Hospital San José', 1990)],
  },
  {
    slug: 'sitio-jardin-japones',
    title: 'Jardín Japonés del Cerro San Cristóbal',
    shortDesc: 'Jardín tradicional japonés inaugurado en 1978 en el Parque Metropolitano.',
    longDesc:
      'El Jardín Japonés en el Parque Metropolitano fue inaugurado en 1978 como obsequio del gobierno japonés a Santiago. Diseñado por Yoshiro Sasayama, recrea un paisaje japonés en miniatura con cascadas, lago y puente de piedra. Es uno de los rincones más visitados del cerro.',
    yearStart: 1978,
    category: 'CULTURA',
    era: 'DICTADURA',
    latitude: -33.4258,
    longitude: -70.6314,
    region: 'Metropolitana',
    comuna: 'Recoleta',
    sources: [MC('jardin-japones', 'Jardín Japonés Parque Metropolitano')],
  },
  {
    slug: 'sitio-zoologico-nacional',
    title: 'Zoológico Nacional',
    shortDesc: 'Inaugurado en 1925 en las faldas del cerro San Cristóbal.',
    longDesc:
      'El Zoológico Nacional se inauguró en 1925 en las faldas del cerro San Cristóbal. Sobre 4,8 hectáreas alberga unas 1.200 aves y mamíferos. Recibe medio millón de visitantes al año. En las últimas décadas se ha modernizado con criterios de bienestar animal y conservación. Es Monumento Histórico.',
    yearStart: 1925,
    category: 'CIENCIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4336,
    longitude: -70.6378,
    region: 'Metropolitana',
    comuna: 'Recoleta',
    sources: [MC('zoo-santiago', 'Zoológico Nacional')],
  },
  {
    slug: 'sitio-funicular-san-cristobal',
    title: 'Funicular del Cerro San Cristóbal',
    shortDesc: 'Funicular inaugurado en 1925 que sube al santuario y al zoológico.',
    longDesc:
      'El Funicular del Cerro San Cristóbal fue inaugurado el 25 de abril de 1925, conectando Pío Nono con la cumbre del cerro. Sus vagones de madera barnizada, ascensores Bonacina italianos y pendientes de hasta 45 grados lo hicieron singular. Recorre 485 metros con desnivel de 215. Es Monumento Histórico desde 2000.',
    yearStart: 1925,
    dateText: '25 de abril de 1925',
    category: 'TRANSPORTE',
    era: 'PARLAMENTARISMO',
    latitude: -33.4274,
    longitude: -70.6308,
    region: 'Metropolitana',
    comuna: 'Recoleta',
    sources: [CMN('Funicular San Cristóbal', 2000)],
  },
  {
    slug: 'sitio-teleferico-san-cristobal',
    title: 'Teleférico del Cerro San Cristóbal',
    shortDesc: 'Teleférico inaugurado en 1980 que conecta el lado oriente del cerro.',
    longDesc:
      'El Teleférico del Cerro San Cristóbal se inauguró en 1980 conectando Tupahue con Cumbre y Pedro de Valdivia. Tras décadas operando con interrupciones, fue completamente reemplazado en 2016 con cabinas modernas suizas. Recorre 4,8 km y es operado por Parquemet.',
    yearStart: 1980,
    category: 'TRANSPORTE',
    era: 'DICTADURA',
    latitude: -33.4214,
    longitude: -70.6253,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('teleferico', 'Teleférico San Cristóbal')],
  },

  // =========================================================================
  // EJES Y AVENIDAS HISTÓRICAS
  // =========================================================================
  {
    slug: 'sitio-alameda-bernardo-ohiggins',
    title: 'Alameda Libertador Bernardo O\'Higgins',
    shortDesc: 'Eje principal de Santiago desde el siglo XVII; reformulada por O\'Higgins en 1818.',
    longDesc:
      'La Alameda nació como un canal con riveras arboladas en el siglo XVII. En 1817-1820 fue convertida por Bernardo O\'Higgins en gran paseo central a imitación europea. Tiene 8 km y atraviesa el centro de Santiago. Cambió de nombre varias veces hasta quedar como Av. Libertador General Bernardo O\'Higgins desde 1937.',
    yearStart: 1818,
    category: 'TRANSPORTE',
    era: 'INDEPENDENCIA',
    latitude: -33.443,
    longitude: -70.6499,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('La Alameda', 'Vicuña Mackenna', 1872)],
  },
  {
    slug: 'sitio-avenida-vicuna-mackenna',
    title: 'Avenida Vicuña Mackenna',
    shortDesc: 'Eje sur-norte abierto en 1875 por el intendente Vicuña Mackenna.',
    longDesc:
      'La avenida Vicuña Mackenna fue trazada en 1875 como parte del "Camino de Cintura" planeado por el intendente Benjamín Vicuña Mackenna. Conecta Plaza Baquedano con la actual rotonda Quilín, atravesando 4 comunas. Es uno de los grandes ejes urbanos del Santiago decimonónico, hoy con vías exclusivas para Transantiago.',
    yearStart: 1875,
    category: 'TRANSPORTE',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4456,
    longitude: -70.633,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('La transformación de Santiago', 'Vicuña Mackenna', 1872)],
  },
  {
    slug: 'sitio-camino-cintura',
    title: 'Camino de Cintura',
    shortDesc: 'Plan de circunvalación que dio origen a las grandes avenidas anulares de Santiago.',
    longDesc:
      'El "Camino de Cintura", concebido por Vicuña Mackenna en 1872, es el origen de las avenidas que rodean el casco central: Vicuña Mackenna, Matta, Blanco Encalada, Brasil, Carmen. Definió el límite urbano del Santiago decimonónico y separó el "Santiago propio" del "Santiago bárbaro" de los suburbios populares.',
    yearStart: 1872,
    category: 'TRANSPORTE',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.46,
    longitude: -70.65,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('La transformación de Santiago', 'Vicuña Mackenna', 1872)],
  },
  {
    slug: 'sitio-vespucio-anular',
    title: 'Avenida Américo Vespucio',
    shortDesc: 'Anillo de circunvalación de Santiago, originalmente trazado en 1929.',
    longDesc:
      'La Avenida Américo Vespucio fue trazada en 1929 como anillo de circunvalación del Gran Santiago, inicialmente como camino rural. Hoy es un eje de 80 km que rodea casi toda la ciudad, parte de él como autopista concesionada (Vespucio Norte y Sur Express). Es columna vertebral del transporte de carga y de buses Transantiago.',
    yearStart: 1929,
    category: 'TRANSPORTE',
    era: 'PARLAMENTARISMO',
    latitude: -33.4828,
    longitude: -70.6383,
    region: 'Metropolitana',
    comuna: 'San Miguel',
    sources: [MC('vespucio', 'Avenida Américo Vespucio')],
  },

  // =========================================================================
  // SAN MIGUEL / LA CISTERNA / EL BOSQUE
  // =========================================================================
  {
    slug: 'sitio-poblacion-victoria-1957',
    title: 'Población La Victoria',
    shortDesc: 'Famosa toma de terrenos del 30 de octubre de 1957, símbolo de la lucha de pobladores.',
    longDesc:
      'La toma de La Victoria fue protagonizada por familias de la Población Zañartu (Talcahuano), tras incendios y desalojos. La noche del 30 de octubre de 1957 ocuparon terrenos en San Miguel y resistieron varios meses. La Iglesia Católica, el Partido Comunista y los pobladores articularon su consolidación. Es considerada la primera toma de gran escala en Chile.',
    yearStart: 1957,
    dateText: '30 de octubre de 1957',
    category: 'POLITICA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.5219,
    longitude: -70.6539,
    region: 'Metropolitana',
    comuna: 'San Miguel',
    featured: true,
    sources: [BN('La Victoria. Una toma', 'Eduardo Valenzuela', 1989)],
  },
  {
    slug: 'sitio-iglesia-san-miguel',
    title: 'Iglesia Matriz de San Miguel',
    shortDesc: 'Templo del antiguo pueblo de San Miguel, reedificado en 1925.',
    longDesc:
      'La Iglesia Matriz de San Miguel está en el sitio del primer asentamiento del antiguo pueblo. Su edificación actual data de 1925 tras incendios y reformas del templo colonial. Le da nombre a la comuna que se constituyó en 1900. Es centro de festividades religiosas tradicionales.',
    yearStart: 1925,
    category: 'RELIGION',
    era: 'PARLAMENTARISMO',
    latitude: -33.499,
    longitude: -70.6483,
    region: 'Metropolitana',
    comuna: 'San Miguel',
    sources: [MC('san-miguel', 'Historia de San Miguel')],
  },
  {
    slug: 'sitio-cementerio-metropolitano',
    title: 'Cementerio Metropolitano',
    shortDesc: 'Inaugurado en 1931 como segundo gran cementerio de Santiago.',
    longDesc:
      'El Cementerio Metropolitano se inauguró en 1931 en La Pintana para descongestionar el Cementerio General. Sus 70 hectáreas albergan tumbas de figuras políticas, artistas y deportistas. Tiene capilla art decó y mausoleos diversos. Es operado por la Sociedad Cementerio Metropolitano.',
    yearStart: 1931,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.5639,
    longitude: -70.6261,
    region: 'Metropolitana',
    comuna: 'La Pintana',
    sources: [MC('cementerio-metropolitano', 'Cementerios de Santiago')],
  },

  // =========================================================================
  // PUENTE ALTO / LA FLORIDA / SUR ORIENTE
  // =========================================================================
  {
    slug: 'sitio-iglesia-puente-alto',
    title: 'Iglesia Matriz de Puente Alto',
    shortDesc: 'Iglesia colonial reedificada en 1900, centro del antiguo pueblo de Puente Alto.',
    longDesc:
      'La Iglesia Matriz de Puente Alto, frente a la Plaza de Armas comunal, ocupa el sitio de la primera capilla de 1745. La edificación actual data de 1900. Le da identidad al casco antiguo de la comuna que era zona rural hasta los años 60. Hoy Puente Alto es la comuna más poblada de Chile (700.000 habitantes).',
    yearStart: 1900,
    category: 'RELIGION',
    era: 'PARLAMENTARISMO',
    latitude: -33.6111,
    longitude: -70.5754,
    region: 'Metropolitana',
    comuna: 'Puente Alto',
    sources: [MC('puente-alto', 'Historia de Puente Alto')],
  },
  {
    slug: 'sitio-papelera-puente-alto',
    title: 'CMPC Planta Puente Alto',
    shortDesc: 'Papelera fundada en 1920, una de las industrias más antiguas de la zona.',
    longDesc:
      'La planta de la Compañía Manufacturera de Papeles y Cartones (CMPC) en Puente Alto fue fundada en 1920 por Luis Matte Larraín. Operó como gran centro industrial papelero por casi un siglo. Cerró su planta original en 2020. Su historia está ligada al desarrollo industrial de Santiago y al barrio obrero de Puente Alto.',
    yearStart: 1920,
    yearEnd: 2020,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.6131,
    longitude: -70.5786,
    region: 'Metropolitana',
    comuna: 'Puente Alto',
    sources: [MC('cmpc', 'CMPC')],
  },
  {
    slug: 'sitio-mall-vespucio',
    title: 'Mall Plaza Vespucio',
    shortDesc: 'Inaugurado en 1990, primer mall del modelo Plaza en Chile.',
    longDesc:
      'El Mall Plaza Vespucio en La Florida fue inaugurado en 1990 por la familia Solari. Fue el primero del grupo Plaza, que después se expandiría por toda Latinoamérica. Cambió radicalmente el comercio de la zona sur de Santiago, antes dependiente del centro. Hoy con 196.000 m² es uno de los más grandes del país.',
    yearStart: 1990,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.5167,
    longitude: -70.5961,
    region: 'Metropolitana',
    comuna: 'La Florida',
    sources: [MC('plaza-vespucio', 'Mall Plaza Vespucio')],
  },

  // =========================================================================
  // VITACURA / LO BARNECHEA / CORDILLERA
  // =========================================================================
  {
    slug: 'sitio-fundo-vitacura',
    title: 'Antiguo Fundo Vitacura',
    shortDesc: 'Las actuales calles de Vitacura ocupan el antiguo fundo del cacique Vitacura.',
    longDesc:
      'El nombre Vitacura viene del cacique picunche Vitacura que dominaba la zona a la llegada de los españoles. Tras la conquista, los terrenos fueron entregados como encomienda. Por siglos fue zona agrícola con grandes haciendas. La urbanización masiva comenzó en los años 60 con la llegada de la avenida Kennedy. Hoy es una de las comunas más caras del país.',
    yearStart: 1541,
    category: 'PUEBLOS_ORIGINARIOS',
    era: 'CONQUISTA',
    latitude: -33.39,
    longitude: -70.575,
    region: 'Metropolitana',
    comuna: 'Vitacura',
    sources: [MC('vitacura-cacique', 'Cacique Vitacura')],
  },
  {
    slug: 'sitio-museo-de-la-moda',
    title: 'Museo de la Moda',
    shortDesc: 'Museo abierto en 2007 en la antigua casa Yarur en Vitacura.',
    longDesc:
      'El Museo de la Moda fue abierto en 2007 por Jorge Yarur Bascuñán en la casa familiar de los años 60 (obra de Sergio Larraín García-Moreno). Alberga una colección de 10.000 piezas de moda histórica, desde el siglo XV hasta hoy. Es uno de los museos más singulares de Sudamérica en su género.',
    yearStart: 2007,
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4022,
    longitude: -70.5964,
    region: 'Metropolitana',
    comuna: 'Vitacura',
    sources: [MC('museo-moda', 'Museo de la Moda')],
  },
  {
    slug: 'sitio-iglesia-los-dominicos',
    title: 'Iglesia y Centro Artesanal Los Dominicos',
    shortDesc: 'Iglesia de 1755 en Las Condes, hoy centro artesanal y cultural.',
    longDesc:
      'La Iglesia de Los Dominicos fue construida en 1755 como capilla de la hacienda Apoquindo. Su estilo colonial de adobe y techo de tejas se conserva pese a restauraciones. Las dependencias contiguas funcionan desde los 80 como Pueblito Los Dominicos, centro artesanal con tiendas, talleres y restaurantes. Es Monumento Nacional.',
    yearStart: 1755,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -33.4022,
    longitude: -70.5269,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [CMN('Los Dominicos', 1985)],
  },
  {
    slug: 'sitio-mall-alto-las-condes',
    title: 'Mall Alto Las Condes',
    shortDesc: 'Inaugurado en 1995 en la pre cordillera, redefinió el comercio del sector oriente.',
    longDesc:
      'El Mall Alto Las Condes se inauguró en 1995 en avenida Kennedy con Padre Hurtado. Diseñado por arquitectos locales con guiño a malls norteamericanos, fue el primer gran mall del oriente alto de Santiago. Su localización aceleró la urbanización del sector pre cordillerano de Las Condes y Lo Barnechea.',
    yearStart: 1995,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.3892,
    longitude: -70.5408,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [MC('alto-las-condes', 'Mall Alto Las Condes')],
  },
  {
    slug: 'sitio-cerro-pochoco',
    title: 'Cerro Pochoco',
    shortDesc: 'Antigua mina de cobre y observatorio astronómico aficionado en Lo Barnechea.',
    longDesc:
      'El Cerro Pochoco fue mina de cobre activa entre 1900 y 1960. En 1985 se instaló en su cumbre el Observatorio Astronómico Pochoco, operado por la Asociación Chilena de Astronomía y Astronáutica. Sigue siendo uno de los pocos observatorios cercanos a Santiago. Su entorno se ha urbanizado pero el cerro mantiene cierto aislamiento.',
    yearStart: 1985,
    category: 'CIENCIA',
    era: 'DICTADURA',
    latitude: -33.3636,
    longitude: -70.4894,
    region: 'Metropolitana',
    comuna: 'Lo Barnechea',
    sources: [MC('pochoco', 'Observatorio Pochoco')],
  },

  // =========================================================================
  // MEMORIA Y DDHH
  // =========================================================================
  {
    slug: 'sitio-londres-38',
    title: 'Londres 38, Casa de la Memoria',
    shortDesc: 'Antiguo cuartel de la DINA en pleno barrio Lastarria, hoy sitio de memoria.',
    longDesc:
      'Londres 38, en pleno centro de Santiago, fue un cuartel de la DINA entre septiembre 1973 y septiembre 1974. Por allí pasaron al menos 96 personas detenidas-desaparecidas o ejecutadas. Hoy es sitio de memoria abierto al público. Su patio interior y celdas son recorribles. Es Monumento Nacional desde 2005.',
    yearStart: 1973,
    yearEnd: 1974,
    category: 'POLITICA',
    era: 'DICTADURA',
    latitude: -33.4395,
    longitude: -70.6481,
    region: 'Metropolitana',
    comuna: 'Santiago',
    featured: true,
    sources: [
      CMN('Londres 38', 2005),
      MC('londres-38', 'Londres 38, Casa de la Memoria'),
    ],
  },
  {
    slug: 'sitio-jose-domingo-canas',
    title: 'José Domingo Cañas 1367',
    shortDesc: 'Cuartel de la DINA en Ñuñoa, hoy sitio de memoria.',
    longDesc:
      'La casa de José Domingo Cañas 1367, en Ñuñoa, fue Cuartel Ollagüe de la DINA en 1974. Por aquí pasaron unas 130 personas detenidas, varias desaparecidas. Tras décadas como propiedad privada, en 2002 fue recuperada por la Fundación 1367 y abierta como sitio de memoria.',
    yearStart: 1974,
    category: 'POLITICA',
    era: 'DICTADURA',
    latitude: -33.4519,
    longitude: -70.6225,
    region: 'Metropolitana',
    comuna: 'Ñuñoa',
    sources: [CMN('José Domingo Cañas 1367', 2010)],
  },
  {
    slug: 'sitio-tres-y-cuatro-alamos',
    title: 'Tres y Cuatro Álamos',
    shortDesc: 'Centros de detención política en San Joaquín, activos entre 1974 y 1976.',
    longDesc:
      'Los campos de prisioneros políticos Tres Álamos y Cuatro Álamos funcionaron en San Joaquín entre 1974 y 1976. Por sus puertas pasaron miles de detenidos, muchos antes de ser desaparecidos. Hoy una placa y proyecto de memoria los recuerdan. Cuatro Álamos era de tránsito (incomunicación); Tres Álamos era prisión.',
    yearStart: 1974,
    yearEnd: 1976,
    category: 'POLITICA',
    era: 'DICTADURA',
    latitude: -33.5031,
    longitude: -70.6342,
    region: 'Metropolitana',
    comuna: 'San Joaquín',
    sources: [CMN('Tres y Cuatro Álamos', 2010)],
  },
  {
    slug: 'sitio-academia-guerra-aerea',
    title: 'Academia de Guerra Aérea (AGA)',
    shortDesc: 'Centro de torturas de la Fuerza Aérea entre 1973 y 1975.',
    longDesc:
      'La Academia de Guerra Aérea (AGA), en Las Condes, fue centro de detención y tortura operado por el SIFA (Servicio de Inteligencia FACh) entre septiembre de 1973 y mediados de 1975. Por allí pasaron unos 600 prisioneros, muchos altos cuadros del MIR y el Partido Socialista. Hoy sigue siendo dependencia militar.',
    yearStart: 1973,
    yearEnd: 1975,
    category: 'POLITICA',
    era: 'DICTADURA',
    latitude: -33.4072,
    longitude: -70.5614,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [CMN('AGA', 2015)],
  },

  // =========================================================================
  // INFRAESTRUCTURA REPUBLICANA Y CIUDAD MODERNA
  // =========================================================================
  {
    slug: 'sitio-edificio-diego-portales-ex',
    title: 'Antiguo edificio Diego Portales (hoy GAM)',
    shortDesc: 'Edificio sede de la Junta Militar entre 1973 y 1990.',
    longDesc:
      'El edificio Diego Portales fue construido en 275 días para la UNCTAD III (1972). Tras el golpe pasó a ser sede de la Junta Militar y del Congreso (cuando éste cambió a Valparaíso). Un incendio en 2006 destruyó parte importante. Reconstruido como GAM en 2010, conserva la torre original.',
    yearStart: 1972,
    category: 'POLITICA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4395,
    longitude: -70.6361,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('diego-portales', 'Edificio Diego Portales')],
  },
  {
    slug: 'sitio-torre-entel',
    title: 'Torre Entel',
    shortDesc: 'Torre de comunicaciones de 127 metros inaugurada en 1974.',
    longDesc:
      'La Torre Entel, en la Alameda con Amunátegui, fue inaugurada el 11 de marzo de 1974 como antena de microondas y mirador. Su torre de 127 metros la convirtió en hito visual del centro. Por décadas fue parte de los logos de Telecom y Entel Chile. La cumbre fue cerrada al público en 2007 por seguridad.',
    yearStart: 1974,
    category: 'CIENCIA',
    era: 'DICTADURA',
    latitude: -33.4426,
    longitude: -70.6541,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('torre-entel', 'Torre Entel')],
  },
  {
    slug: 'sitio-edificio-las-torres-san-borja',
    title: 'Torres de San Borja',
    shortDesc: 'Conjunto residencial moderno de 1971 en pleno centro.',
    longDesc:
      'El conjunto Remodelación San Borja, conocido como "Torres de San Borja", se inauguró en 1971 sobre los terrenos del antiguo Hospital San Borja. Compuesto por 21 torres de 13 a 23 pisos diseñadas por la CORMU. Acoge a 8.000 habitantes. Modelo de "modernidad social" del gobierno de Frei. La torre 14 colapsó por el terremoto de 1985.',
    yearStart: 1971,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4406,
    longitude: -70.6412,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('san-borja', 'Conjunto San Borja')],
  },
  {
    slug: 'sitio-edificio-cuerpo-bomberos',
    title: 'Cuerpo de Bomberos de Santiago',
    shortDesc: 'Sede principal del Cuerpo de Bomberos, fundado en 1863 tras el incendio de la Compañía.',
    longDesc:
      'El Cuerpo de Bomberos de Santiago fue fundado en diciembre de 1863, semanas después de la tragedia del incendio de la Iglesia de la Compañía. Es totalmente voluntario, modelo único en Latinoamérica. Su Cuartel General en calle Santo Domingo data de 1893. Es la institución más antigua de bomberos del país.',
    yearStart: 1863,
    category: 'POLITICA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4347,
    longitude: -70.6515,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Historia del Cuerpo de Bomberos', 'Carlos Rudloff', 1963)],
  },

  // =========================================================================
  // CULTURA DE NUEVO SIGLO
  // =========================================================================
  {
    slug: 'sitio-museo-violeta-parra',
    title: 'Museo Violeta Parra',
    shortDesc: 'Museo dedicado a la cantautora, abierto en 2015 en pleno centro.',
    longDesc:
      'El Museo Violeta Parra abrió sus puertas en 2015 en avenida Vicuña Mackenna, en un edificio de cuatro pisos. Conserva sus arpilleras, óleos, instrumentos y manuscritos. Es administrado por la Fundación Violeta Parra. En 2020 sufrió un incendio en el contexto del estallido social pero fue restaurado.',
    yearStart: 2015,
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4445,
    longitude: -70.6336,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('museo-violeta', 'Museo Violeta Parra')],
  },
  {
    slug: 'sitio-cinema-hoyts-huerfanos',
    title: 'Antiguo Cine Huérfanos',
    shortDesc: 'Cine emblemático del centro, abierto en 1934 y cerrado en 2003.',
    longDesc:
      'El Cine Huérfanos abrió en 1934 como una de las salas más grandes de Sudamérica con 2.400 butacas, palcos y galerías. Por su escenario pasaron Carlos Gardel, Pedro Vargas, los grandes shows de la radio. Fue el cine más popular del centro hasta su cierre en 2003. El edificio fue subdividido en multicines.',
    yearStart: 1934,
    yearEnd: 2003,
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4393,
    longitude: -70.6498,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('cine-huerfanos', 'Cines del centro de Santiago')],
  },
  {
    slug: 'sitio-cine-arte-alameda-incendiado',
    title: 'Antiguo Cine Arte Alameda',
    shortDesc: 'Sala emblemática del cine arte, destruida por incendio en 2019.',
    longDesc:
      'El Cine Arte Alameda funcionó desde 1991 en una antigua casona de la Alameda como sala de cine independiente, club nocturno y centro cultural. Fue incendiado durante el estallido social del 18 de octubre de 2019. Su comunidad se reorganizó como "Centro Arte Alameda Casa" en otra ubicación. El sitio original aún espera reconstrucción.',
    yearStart: 1991,
    yearEnd: 2019,
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4395,
    longitude: -70.6358,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('arte-alameda', 'Centro Arte Alameda')],
  },
  {
    slug: 'sitio-circo-arte-circo-del-mundo',
    title: 'Circo del Mundo',
    shortDesc: 'Escuela y compañía de circo social fundada en 1995 en Cerrillos.',
    longDesc:
      'El Circo del Mundo - Chile fue fundado en 1995 con apoyo del Cirque du Soleil canadiense como proyecto de circo social. Su sede en Cerrillos forma a niños y jóvenes de barrios vulnerables en artes circenses. Ha producido decenas de espectáculos y giras internacionales. Es referente latinoamericano del arte circense contemporáneo.',
    yearStart: 1995,
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4922,
    longitude: -70.7036,
    region: 'Metropolitana',
    comuna: 'Cerrillos',
    sources: [MC('circo-del-mundo', 'Circo del Mundo Chile')],
  },

  // =========================================================================
  // ESPACIOS PÚBLICOS Y MONUMENTOS
  // =========================================================================
  {
    slug: 'sitio-monumento-ohiggins-alameda',
    title: 'Monumento ecuestre a O\'Higgins',
    shortDesc: 'Estatua ecuestre del Libertador inaugurada en 1872 en la Alameda.',
    longDesc:
      'La estatua ecuestre de Bernardo O\'Higgins, obra del francés Albert-Ernest Carrier-Belleuse, fue inaugurada el 18 de septiembre de 1872 en la Alameda. Su pedestal de granito data de 1922. Fue restaurada varias veces. Es uno de los monumentos más fotografiados de Santiago. Está al frente de la Plaza Bulnes.',
    yearStart: 1872,
    dateText: '18 de septiembre de 1872',
    category: 'POLITICA',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4434,
    longitude: -70.6553,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Monumento O\'Higgins', 1980)],
  },
  {
    slug: 'sitio-altar-patria',
    title: 'Altar de la Patria',
    shortDesc: 'Mausoleo del Libertador O\'Higgins en la Plaza de la Ciudadanía.',
    longDesc:
      'El Altar de la Patria, en la Plaza de la Ciudadanía frente a La Moneda, alberga los restos del Libertador Bernardo O\'Higgins desde 1979. Fue diseñado por Juan Martínez Gutiérrez como subterráneo cilíndrico con la cripta central. Tiene una llama eterna. Es escenario de homenajes oficiales y desfiles militares.',
    yearStart: 1979,
    category: 'POLITICA',
    era: 'DICTADURA',
    latitude: -33.444,
    longitude: -70.6536,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Altar de la Patria', 1979)],
  },
  {
    slug: 'sitio-estatua-virgen-cerro-blanco',
    title: 'Centro ceremonial mapuche del Cerro Blanco',
    shortDesc: 'Sitio ritual mapuche de la zona urbana, abierto al público desde 2005.',
    longDesc:
      'En el Cerro Blanco de Recoleta, sitio sagrado prehispánico, opera desde 2005 un Centro Ceremonial Mapuche reconocido por el Consejo de Monumentos Nacionales. Tiene un rewe (altar ceremonial), espacios para nguillatún y celebraciones del We Tripantü (Año Nuevo Mapuche). Es uno de los pocos espacios urbanos para la espiritualidad mapuche.',
    yearStart: 2005,
    category: 'PUEBLOS_ORIGINARIOS',
    era: 'TRANSICION',
    latitude: -33.4128,
    longitude: -70.6411,
    region: 'Metropolitana',
    comuna: 'Recoleta',
    sources: [CMN('Centro Ceremonial Cerro Blanco', 2005)],
  },
  {
    slug: 'sitio-templo-bahai-sudamerica',
    title: 'Templo Bahá\'í para Sudamérica',
    shortDesc: 'Único templo bahá\'í de Sudamérica, inaugurado en 2016 en Peñalolén.',
    longDesc:
      'El Templo Bahá\'í de Sudamérica, en las faldas precordilleranas de Peñalolén, fue inaugurado el 19 de octubre de 2016. Diseñado por el canadiense Hariri Pontarini, su cúpula traslúcida de mármol portugués y cristal envuelto en bronce es uno de los íconos arquitectónicos contemporáneos del país. Está abierto al público todos los días.',
    yearStart: 2016,
    dateText: '19 de octubre de 2016',
    category: 'RELIGION',
    era: 'TRANSICION',
    latitude: -33.4914,
    longitude: -70.5039,
    region: 'Metropolitana',
    comuna: 'Peñalolén',
    sources: [MC('templo-bahai', 'Templo Bahá\'í de Sudamérica')],
  },

  // =========================================================================
  // ESTACIONES DE METRO HISTÓRICAS Y EJES URBANOS
  // =========================================================================
  {
    slug: 'sitio-estacion-metro-republica',
    title: 'Estación República del Metro',
    shortDesc: 'Estación de Línea 1 inaugurada en 1975 con estética del barrio universitario.',
    longDesc:
      'Inaugurada el 31 de marzo de 1977 como parte del primer tramo Salvador-Las Rejas, la estación República sirve al Barrio República y a las universidades de la zona. Su nombre proviene de la avenida República, eje del barrio universitario. Es uno de los nodos de transporte estudiantil del centro.',
    yearStart: 1977,
    category: 'TRANSPORTE',
    era: 'DICTADURA',
    latitude: -33.4453,
    longitude: -70.661,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('metro-republica', 'Estaciones del Metro de Santiago')],
  },
  {
    slug: 'sitio-estacion-metro-tobalaba',
    title: 'Estación Tobalaba del Metro',
    shortDesc: 'Estación de transbordo Línea 1 / Línea 4, inaugurada en 1980 y ampliada en 2005.',
    longDesc:
      'La estación Tobalaba se inauguró el 31 de marzo de 1980 como parte de la extensión oriente de la Línea 1. En 2005, con la apertura de la Línea 4, se transformó en estación de transbordo y se construyó la nueva estación con la Torre Titanium adyacente. Es una de las estaciones con más afluencia del sistema.',
    yearStart: 1980,
    category: 'TRANSPORTE',
    era: 'DICTADURA',
    latitude: -33.4181,
    longitude: -70.6017,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('metro-tobalaba', 'Estación Tobalaba')],
  },

  // =========================================================================
  // CASAS DE ESCRITORES Y ARTISTAS
  // =========================================================================
  {
    slug: 'sitio-casa-vicente-huidobro',
    title: 'Casa de Vicente Huidobro',
    shortDesc: 'Casona donde vivió y murió el poeta creacionista Vicente Huidobro.',
    longDesc:
      'Vicente Huidobro vivió en una casa de calle La Concepción 244, Providencia, durante sus últimos años, hasta su muerte en Cartagena en 1948. Su casa de Santiago era centro de tertulias literarias. Hoy alberga oficinas. La placa que la recuerda es un homenaje informal al fundador del creacionismo y figura de las vanguardias.',
    yearStart: 1940,
    yearEnd: 1948,
    category: 'CULTURA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4222,
    longitude: -70.6056,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [BN('Vicente Huidobro: vida y obra', 'René de Costa', 1984)],
  },
  {
    slug: 'sitio-casa-pedro-prado',
    title: 'Casa de Pedro Prado (los Diez)',
    shortDesc: 'Casa donde se reunía el grupo Los Diez en los años 1910.',
    longDesc:
      'En la calle Carmen, los hermanos Pedro y Francisco Prado tenían una casa que albergó al Grupo Los Diez (1916-1925), círculo literario y artístico que renovó el panorama cultural chileno. Eduardo Barrios, Augusto D\'Halmar, Carlos Mondaca, entre otros, formaban parte. La casa original fue demolida en los 60.',
    yearStart: 1916,
    yearEnd: 1925,
    category: 'CULTURA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4458,
    longitude: -70.6489,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('El Grupo de Los Diez', 'Hernán Díaz Arrieta', 1973)],
  },
  {
    slug: 'sitio-casa-roberto-matta',
    title: 'Casa de Roberto Matta',
    shortDesc: 'Casa familiar del pintor surrealista Roberto Matta en el centro.',
    longDesc:
      'En calle Compañía, la casa familiar donde nació en 1911 el pintor surrealista Roberto Matta Echaurren ya no existe. Una placa la recuerda. Matta murió en Italia en 2002 pero su huella en Chile es honrada en el Museo Bellas Artes con varias obras.',
    yearStart: 1911,
    category: 'CULTURA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4391,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Roberto Matta', 'Eduardo Carrasco', 1987)],
  },

  // =========================================================================
  // ARQUITECTURA INDUSTRIAL Y FERROVIARIA
  // =========================================================================
  {
    slug: 'sitio-maestranza-san-eugenio',
    title: 'Maestranza Ferroviaria San Eugenio',
    shortDesc: 'Centro de mantención de los Ferrocarriles del Estado, en uso desde 1875.',
    longDesc:
      'La Maestranza San Eugenio, en Estación Central, se construyó en 1875 como centro de mantención de la red ferroviaria. Sus galpones de hierro y vidrio fueron pioneros en la arquitectura industrial chilena. Aún en operación reducida bajo EFE, parte de sus terrenos se han desarrollado como Pueblo San Eugenio (2019).',
    yearStart: 1875,
    category: 'TRANSPORTE',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.4593,
    longitude: -70.6772,
    region: 'Metropolitana',
    comuna: 'Estación Central',
    sources: [MC('san-eugenio', 'Maestranza San Eugenio')],
  },
  {
    slug: 'sitio-fabrica-yarur',
    title: 'Antigua Fábrica Yarur',
    shortDesc: 'Fábrica textil emblemática de los años 30, símbolo del proletariado de izquierda.',
    longDesc:
      'La Fábrica Textil Yarur, fundada en 1936 en San Miguel por la familia palestina del mismo nombre, llegó a emplear a 4.000 obreros. Su huelga de 1962 y la nacionalización por Allende en 1971 son hitos de la historia del movimiento obrero chileno. Cerró en 1991. Hoy parte del terreno alberga el Museo de la Solidaridad Salvador Allende.',
    yearStart: 1936,
    yearEnd: 1991,
    category: 'ECONOMIA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4936,
    longitude: -70.6483,
    region: 'Metropolitana',
    comuna: 'San Miguel',
    sources: [BN('Yarur. Una historia', 'Peter Winn', 1986)],
  },

  // =========================================================================
  // CIERRE: HITOS DEL ESTALLIDO Y PANDEMIA
  // =========================================================================
  {
    slug: 'sitio-museo-memoria-derechos-humanos',
    title: 'Museo de la Memoria y los Derechos Humanos',
    shortDesc: 'Inaugurado en 2010, edificio elevado con la memoria de la dictadura.',
    longDesc:
      'El Museo de la Memoria y los Derechos Humanos, en Matucana 501, fue inaugurado el 11 de enero de 2010 por la presidenta Bachelet. Su edificio elevado de la firma brasileña Mario Figueroa simboliza la suspensión de las víctimas. Su misión es resguardar la memoria de las violaciones de DDHH durante la dictadura. Es referente latinoamericano.',
    yearStart: 2010,
    dateText: '11 de enero de 2010',
    category: 'POLITICA',
    era: 'TRANSICION',
    latitude: -33.4399,
    longitude: -70.685,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('mmdh', 'Museo de la Memoria y los Derechos Humanos')],
  },
  {
    slug: 'sitio-monumento-victimas-estallido',
    title: 'Plaza de la Dignidad: monumentos y memoriales',
    shortDesc: 'Sitio donde se concentraron las protestas y memoriales del estallido social.',
    longDesc:
      'Durante el estallido social de 2019-2020, la Plaza Baquedano (rebautizada como Plaza Dignidad) se convirtió en epicentro de protestas semanales. Los manifestantes instalaron placas con nombres de víctimas, especialmente quienes perdieron sus ojos por perdigones policiales. Tras la remoción de la estatua de Baquedano (marzo 2021) el sitio sigue siendo simbólico.',
    yearStart: 2019,
    category: 'POLITICA',
    era: 'TRANSICION',
    latitude: -33.4372,
    longitude: -70.6346,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('plaza-dignidad', 'Plaza Baquedano / Plaza Dignidad')],
  },
  {
    slug: 'sitio-centros-vacunacion-2021',
    title: 'Centros de vacunación masivos COVID',
    shortDesc: 'Estadios y plazas convertidos en centros de vacunación durante 2021.',
    longDesc:
      'Durante la campaña de vacunación contra el COVID-19 (febrero 2021 en adelante), Chile transformó estadios, plazas y locales emblemáticos en centros de vacunación masiva. El Estadio Bicentenario de La Florida, el Estadio Nacional, el GAM y decenas de gimnasios municipales operaron 24/7. Chile lideró la vacunación mundial llegando a 92% con esquema completo.',
    yearStart: 2021,
    category: 'POLITICA',
    era: 'TRANSICION',
    latitude: -33.5219,
    longitude: -70.5933,
    region: 'Metropolitana',
    comuna: 'La Florida',
    sources: [MC('vacunacion-covid', 'Vacunación COVID-19 en Chile')],
  },
]

export const SANTIAGO_SITIOS_VERSION = '0.1.0'
