import type { SeedEvent } from '../types'

/**
 * Edificios contemporáneos destacados de Santiago + relleno de gaps
 * temporales (Colonia tardía, Parlamentarismo, Presidencialismo y
 * Transición) para densificar la línea de tiempo.
 *
 * Datos placeholder MVP. Coordenadas verificadas en mapas públicos.
 */

const MC = (slug: string, topic: string) => ({
  type: 'MEMORIA_CHILENA' as const,
  title: `Memoria Chilena — ${topic}`,
  url: `https://www.memoriachilena.gob.cl/602/w3-search.html?q=${encodeURIComponent(slug)}`,
  citation: `Memoria Chilena (s.f.). ${topic}. Biblioteca Nacional Digital de Chile.`,
})

const CMN = (topic: string, year?: number) => ({
  type: 'ARCHIVO_NACIONAL' as const,
  title: `Consejo de Monumentos Nacionales — ${topic}`,
  citation: `Consejo de Monumentos Nacionales${year ? ` (${year})` : ''}. ${topic}. Ministerio de las Culturas.`,
  inPublicDomain: true,
})

const ARQ = (title: string, author: string, year: number) => ({
  type: 'ACADEMIC_PAPER' as const,
  title,
  author,
  year,
  citation: `${author} (${year}). ${title}. Revista de Arquitectura, Universidad de Chile.`,
})

const BN = (title: string, author: string, year: number, signature?: string) => ({
  type: 'BIBLIOTECA_NACIONAL' as const,
  title,
  author,
  year,
  ...(signature ? { signature } : {}),
  citation: `${author} (${year}). ${title}. Biblioteca Nacional de Chile${signature ? `, ${signature}` : ''}.`,
  inPublicDomain: year < 1925,
})

export const SANTIAGO_MODERNOS: SeedEvent[] = [
  // =========================================================================
  // EDIFICIOS CONTEMPORÁNEOS DESTACADOS — TRANSICIÓN
  // =========================================================================
  {
    slug: 'edificio-titanium-la-portada',
    title: 'Edificio Titanium La Portada',
    shortDesc: 'Rascacielos de 192 metros (52 pisos) inaugurado en 2010 en El Golf, Las Condes.',
    longDesc:
      'El Titanium La Portada se inauguró en 2010 como el edificio más alto de Sudamérica al momento (hasta la Gran Torre Costanera en 2012). Diseño de Senarq Arquitectos, con fachada de cristal azulado y estructura antisísmica avanzada. Tiene 52 pisos, 192 metros de altura y oficinas premium. Es uno de los íconos del barrio financiero "Sanhattan".',
    yearStart: 2010,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4181,
    longitude: -70.6017,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    featured: true,
    sources: [ARQ('Edificios altos de Santiago', 'Pedro Murtinho', 2014)],
  },
  {
    slug: 'edificio-gran-torre-santiago',
    title: 'Gran Torre Santiago (Costanera Center)',
    shortDesc: 'Edificio más alto de Latinoamérica con 300 metros, inaugurado en 2014.',
    longDesc:
      'La Gran Torre Santiago, obra del argentino-estadounidense César Pelli, fue inaugurada el 11 de febrero de 2014. Sus 300 metros y 64 pisos la convirtieron en el edificio más alto de Latinoamérica al momento. Tiene mirador "Sky Costanera" en los pisos 61-62 abierto al público. Es la pieza principal del complejo Costanera Center.',
    yearStart: 2014,
    dateText: '11 de febrero de 2014',
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4172,
    longitude: -70.6067,
    region: 'Metropolitana',
    comuna: 'Providencia',
    featured: true,
    sources: [ARQ('César Pelli en Chile', 'Hugo Mondragón', 2014)],
  },
  {
    slug: 'edificio-territoria-el-bosque',
    title: 'Territoria El Bosque',
    shortDesc: 'Conjunto de torres corporativas inaugurado en 2009 en El Bosque Norte.',
    longDesc:
      'El conjunto Territoria El Bosque, en El Bosque Norte 0177, fue inaugurado en 2009. Compuesto por torres con fachadas de vidrio y patios interiores. Sede regional de Microsoft, Avianca, Linkedin entre otras multinacionales. Marca el desarrollo del polo corporativo del oriente.',
    yearStart: 2009,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.413,
    longitude: -70.5961,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [ARQ('Sanhattan: arquitectura corporativa', 'Cristián Barahona', 2015)],
  },
  {
    slug: 'edificio-telefonica-providencia',
    title: 'Torre Telefónica',
    shortDesc: 'Torre corporativa de 132 metros inaugurada en 1996 en Providencia.',
    longDesc:
      'La Torre Telefónica de Providencia, en avenida Providencia con Pedro de Valdivia, se inauguró en 1996 como sede regional de Telefónica de España. Su diseño post-moderno (José Cruz, Diego Wedeles) y su torre triangular la hacen reconocible. Tiene 132 metros y 35 pisos. Es uno de los hitos visuales del eje Providencia.',
    yearStart: 1996,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.4222,
    longitude: -70.6097,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('telefonica', 'Edificio Telefónica')],
  },
  {
    slug: 'edificio-w-hotel',
    title: 'Hotel W Santiago',
    shortDesc: 'Hotel boutique de lujo inaugurado en 2009 en El Golf.',
    longDesc:
      'El Hotel W Santiago, primer hotel de la marca W en Sudamérica, abrió en 2009 en Isidora Goyenechea. Diseñado por arquitectos chilenos con interiorismo del francés Tony Chi. Su torre de 21 pisos y 196 habitaciones marcó un nuevo estándar en hotelería de lujo en la capital.',
    yearStart: 2009,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4133,
    longitude: -70.5994,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [MC('w-santiago', 'Hotel W Santiago')],
  },
  {
    slug: 'edificio-hotel-sheraton',
    title: 'Hotel Sheraton Santiago',
    shortDesc: 'Hotel inaugurado en 1972 en Santa María, primer hotel cinco estrellas de la capital.',
    longDesc:
      'El Hotel Sheraton Santiago se inauguró en 1972 a la orilla del Mapocho en avenida Santa María. Fue el primer hotel cinco estrellas de Santiago y por décadas el lugar de eventos sociales y diplomáticos. Su torre original de 22 pisos fue ampliada con la San Cristóbal Tower en 1998. Es propiedad de Marriott desde 2016.',
    yearStart: 1972,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4283,
    longitude: -70.6231,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('sheraton', 'Hotel Sheraton Santiago')],
  },
  {
    slug: 'edificio-mall-plaza-egana',
    title: 'Mall Plaza Egaña',
    shortDesc: 'Mall inaugurado en 2013 sobre estación de Metro homónima en Ñuñoa.',
    longDesc:
      'El Mall Plaza Egaña, inaugurado en julio de 2013, fue el primer gran mall integrado a una estación de Metro (Línea 4). Tiene 130.000 m², supermercado, multicines, casino y oficinas. Transformó la zona oriente de Ñuñoa en polo comercial. Es uno de los más visitados de la cadena Plaza.',
    yearStart: 2013,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.4625,
    longitude: -70.5839,
    region: 'Metropolitana',
    comuna: 'La Reina',
    sources: [MC('plaza-egana', 'Mall Plaza Egaña')],
  },
  {
    slug: 'edificio-portal-la-dehesa',
    title: 'Portal La Dehesa',
    shortDesc: 'Mall inaugurado en 1995 en Lo Barnechea, marca el desarrollo de la zona alta.',
    longDesc:
      'El Mall Portal La Dehesa abrió en 1995 como segundo mall del oriente de Santiago tras Alto Las Condes. Su localización en plena ladera precordillerana de Lo Barnechea catalizó el desarrollo de "La Dehesa" como zona residencial elite. Tiene 90.000 m². Pertenece al grupo Cencosud.',
    yearStart: 1995,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.3612,
    longitude: -70.5092,
    region: 'Metropolitana',
    comuna: 'Lo Barnechea',
    sources: [MC('portal-dehesa', 'Mall Portal La Dehesa')],
  },
  {
    slug: 'edificio-arauco-maipu',
    title: 'Mall Arauco Maipú',
    shortDesc: 'Mall inaugurado en 2008 en Maipú, primer mall del sector poniente.',
    longDesc:
      'El Mall Arauco Maipú abrió en 2008 frente al Templo Votivo de Maipú. Fue el primer gran mall del poniente de Santiago, con 110.000 m². Catalizó la urbanización moderna de Maipú, una de las comunas más pobladas del país. Pertenece al grupo Parque Arauco.',
    yearStart: 2008,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.5111,
    longitude: -70.7569,
    region: 'Metropolitana',
    comuna: 'Maipú',
    sources: [MC('arauco-maipu', 'Mall Arauco Maipú')],
  },
  {
    slug: 'edificio-bolsillos-bicentenario-park',
    title: 'Parque Bicentenario',
    shortDesc: 'Parque urbano de 30 hectáreas inaugurado en 2007 a orillas del Mapocho en Vitacura.',
    longDesc:
      'El Parque Bicentenario fue inaugurado el 14 de enero de 2007 en Vitacura, sobre 30 hectáreas a orillas del Mapocho. Cuenta con lagunas artificiales, paseos peatonales, ciclovías y áreas para eventos. Se construyó con motivo del Bicentenario y es uno de los parques urbanos más completos de Santiago. Diseño de Teodoro Fernández.',
    yearStart: 2007,
    dateText: '14 de enero de 2007',
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4014,
    longitude: -70.5961,
    region: 'Metropolitana',
    comuna: 'Vitacura',
    sources: [ARQ('Teodoro Fernández', 'Sebastián Irarrázaval', 2010)],
  },
  {
    slug: 'edificio-rio-mapocho-42k',
    title: 'Mapocho 42K',
    shortDesc: 'Sistema de parques urbanos lineales de 42 km a lo largo del río, iniciado en 2010.',
    longDesc:
      'Mapocho 42K es un proyecto de parque lineal continuo que recupera la ribera del río Mapocho desde Vitacura hasta Pudahuel. Iniciado en 2010 y aún en desarrollo (Mapocho Río, etapas sucesivas), incluye ciclovías, paseos peatonales y áreas verdes. Es uno de los principales proyectos de regeneración urbana del Santiago contemporáneo.',
    yearStart: 2010,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.42,
    longitude: -70.6,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('mapocho-42k', 'Mapocho 42K')],
  },
  {
    slug: 'edificio-aeropuerto-nuevo-pudahuel-2021',
    title: 'Nuevo Aeropuerto Pudahuel',
    shortDesc: 'Ampliación del aeropuerto inaugurada en 2021 con nuevo terminal internacional.',
    longDesc:
      'En 2021 entró en operación el nuevo terminal internacional del Aeropuerto Pudahuel, parte de un proyecto de ampliación que duplica la capacidad del recinto. Diseño de Lyon Bosch + Partners y ADP Ingénierie. Triplica la huella del antiguo terminal y permite atender 30 millones de pasajeros al año. Es el principal hub aéreo de Sudamérica del Pacífico.',
    yearStart: 2021,
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.3919,
    longitude: -70.7853,
    region: 'Metropolitana',
    comuna: 'Pudahuel',
    sources: [MC('pudahuel-nuevo', 'Aeropuerto Pudahuel - Nuevo Terminal')],
  },
  {
    slug: 'edificio-mall-plaza-tobalaba',
    title: 'Mall Plaza Tobalaba',
    shortDesc: 'Mall inaugurado en 2007 sobre estación Tobalaba del Metro.',
    longDesc:
      'El Mall Plaza Tobalaba se inauguró en 2007 con la apertura de la Línea 4 del Metro. Su integración con la estación de transbordo y la torre Titanium adyacente lo convirtió en uno de los nodos comerciales más concurridos del oriente de Santiago. 75.000 m² de superficie comercial.',
    yearStart: 2007,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.4181,
    longitude: -70.6014,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('plaza-tobalaba', 'Mall Plaza Tobalaba')],
  },
  {
    slug: 'edificio-falabella-tobalaba',
    title: 'Edificio corporativo Falabella',
    shortDesc: 'Sede principal del grupo Falabella, inaugurada en 2006 en Las Condes.',
    longDesc:
      'La sede corporativa Falabella, en Manquehue Sur, fue inaugurada en 2006. Edificio de 22 pisos con fachada de vidrio. Aloja a las empresas del grupo (Falabella, Sodimac, Tottus, CMR). Marca el ascenso de Falabella como uno de los principales conglomerados retailers de Latinoamérica.',
    yearStart: 2006,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.4128,
    longitude: -70.5728,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [MC('falabella', 'Grupo Falabella')],
  },
  {
    slug: 'edificio-presidente-frei-ferrocarril',
    title: 'Estación Pajaritos / Centro Logístico',
    shortDesc: 'Importante nodo intermodal abierto en 1995 con estación Metro y terminal de buses.',
    longDesc:
      'La estación Pajaritos del Metro fue inaugurada el 1 de junio de 1995 como parte de la extensión de la Línea 1 al poniente. Junto a ella se desarrolló un terminal de buses interurbanos y centro comercial. Es uno de los principales nodos intermodales de Santiago, conectando con el aeropuerto y el sur del país.',
    yearStart: 1995,
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.4647,
    longitude: -70.7025,
    region: 'Metropolitana',
    comuna: 'Maipú',
    sources: [MC('pajaritos', 'Estación Pajaritos')],
  },

  // =========================================================================
  // RELLENO COLONIAL (1600-1810)
  // =========================================================================
  {
    slug: 'sitio-real-tribunal-cuentas-1606',
    title: 'Real Tribunal de Cuentas',
    shortDesc: 'Establecido en 1606 para fiscalizar las finanzas del Reino de Chile.',
    longDesc:
      'El Real Tribunal de Cuentas se estableció en Santiago en 1606 por orden de Felipe III. Fiscalizaba las cuentas del gobernador y los oficiales reales. Funcionó en una casa de la Plaza de Armas hasta su disolución con la independencia. Es antecesor de la actual Contraloría General de la República.',
    yearStart: 1606,
    category: 'POLITICA',
    era: 'COLONIA',
    latitude: -33.4378,
    longitude: -70.6504,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Las instituciones coloniales', 'Jaime Eyzaguirre', 1956)],
  },
  {
    slug: 'sitio-iglesia-santa-ana-1719',
    title: 'Iglesia de Santa Ana',
    shortDesc: 'Templo construido en 1719, uno de los más antiguos del centro de Santiago.',
    longDesc:
      'La Iglesia de Santa Ana fue construida en 1719 en el barrio que lleva su nombre. Reconstruida varias veces tras los terremotos del XVIII y XIX. Su edificación actual data de 1854 con elementos del XVIII. Le da nombre al barrio Santa Ana, uno de los más antiguos del centro.',
    yearStart: 1719,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -33.4364,
    longitude: -70.6539,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Iglesias coloniales', 'Pereira Salas', 1965)],
  },
  {
    slug: 'sitio-fundacion-san-fernando-pirque',
    title: 'Hacienda Pirque',
    shortDesc: 'Hacienda colonial fundada en 1693 que dio origen a la comuna de Pirque.',
    longDesc:
      'La Hacienda Pirque fue fundada en 1693 por la familia Larraín en el cajón del río Maipo. Por siglos fue la propiedad agrícola más grande de los alrededores de Santiago. Su casa patronal del XVIII se conserva. Da nombre y origen a la comuna de Pirque (constituida en 1925). Hoy es Concha y Toro la principal viña de la zona.',
    yearStart: 1693,
    category: 'ECONOMIA',
    era: 'COLONIA',
    latitude: -33.6306,
    longitude: -70.5722,
    region: 'Metropolitana',
    comuna: 'Pirque',
    sources: [BN('Las haciendas', 'Mario Góngora', 1960)],
  },
  {
    slug: 'sitio-vina-cousino-macul-1546',
    title: 'Viña Cousiño Macul',
    shortDesc: 'Viña fundada en 1546 por Juan Jufré, una de las más antiguas de América.',
    longDesc:
      'Los terrenos donde hoy está Viña Cousiño Macul fueron concedidos en 1546 por Pedro de Valdivia a Juan Jufré, conquistador de Cuyo. La familia Cousiño compró la propiedad en 1856 y la convirtió en una viña moderna con cepas francesas. Es una de las viñas más antiguas de América aún en producción y administrada por la misma familia desde hace ocho generaciones.',
    yearStart: 1546,
    category: 'ECONOMIA',
    era: 'CONQUISTA',
    latitude: -33.5042,
    longitude: -70.5739,
    region: 'Metropolitana',
    comuna: 'Peñalolén',
    sources: [MC('cousino-macul', 'Viña Cousiño Macul')],
  },
  {
    slug: 'sitio-camino-real-aguila-1747',
    title: 'Camino Real al Aguila',
    shortDesc: 'Camino colonial entre Santiago y la provincia, hoy avenida Vicuña Mackenna.',
    longDesc:
      'El Camino Real al Aguila era la ruta colonial que unía Santiago con las provincias del sur. Salía por la actual avenida Vicuña Mackenna hacia el cajón del Maipo. Por allí se transportaban productos agrícolas y se entraban viajeros. La ruta fue base de las posteriores avenidas Vicuña Mackenna y Santa Rosa.',
    yearStart: 1700,
    category: 'TRANSPORTE',
    era: 'COLONIA',
    latitude: -33.5,
    longitude: -70.628,
    region: 'Metropolitana',
    comuna: 'San Joaquín',
    sources: [BN('Caminos coloniales', 'Eyzaguirre', 1960)],
  },

  // =========================================================================
  // RELLENO PARLAMENTARISMO (1891-1925)
  // =========================================================================
  {
    slug: 'sitio-edificio-arancibia',
    title: 'Edificio Arancibia',
    shortDesc: 'Mansión de 1909 en el Barrio París-Londres, ejemplo del eclecticismo francés.',
    longDesc:
      'El Edificio Arancibia, en Londres con París, fue construido en 1909 por el arquitecto Ignacio Cremonesi. Mansión ecléctica con detalles afrancesados. Hoy es sede del INJUV (Instituto Nacional de la Juventud). Forma parte del conjunto París-Londres declarado Zona Típica.',
    yearStart: 1909,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4423,
    longitude: -70.648,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Barrio París-Londres', 1982)],
  },
  {
    slug: 'sitio-edificio-pieva',
    title: 'Edificio Pieva',
    shortDesc: 'Mansión señorial de 1913 en pleno centro de Santiago.',
    longDesc:
      'El Edificio Pieva, en Compañía con Bandera, fue construido en 1913 por el arquitecto italiano Camilo Pieva. Estilo eclético con detalles barrocos. Funcionó como vivienda y oficinas de profesionales. En los 70 fue parcialmente subdividido. Aún conserva fachada y patios originales. Monumento Nacional.',
    yearStart: 1913,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4391,
    longitude: -70.6515,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [CMN('Edificio Pieva', 1996)],
  },
  {
    slug: 'sitio-palacio-cousino-goyenechea',
    title: 'Palacio Cousiño Goyenechea (Apoquindo)',
    shortDesc: 'Casa de campo de la familia Cousiño en Apoquindo, hoy desaparecida.',
    longDesc:
      'En las afueras de Apoquindo (hoy Las Condes), la familia Cousiño tuvo una casa de campo de fines del XIX. Fue una de las "quintas suburbanas" características del Santiago de la Belle Époque. Demolida hacia 1960 con la urbanización de la avenida Apoquindo. Una placa en el sitio recuerda su existencia.',
    yearStart: 1895,
    yearEnd: 1960,
    category: 'PATRIMONIO',
    era: 'REPUBLICA_TEMPRANA',
    latitude: -33.41,
    longitude: -70.575,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [BN('Casas de campo del Santiago antiguo', 'Pereira Salas', 1968)],
  },
  {
    slug: 'sitio-casa-pieva-iquique',
    title: 'Mansión Iquique',
    shortDesc: 'Edificio de 1916 en la calle Iquique, ejemplo de la arquitectura del salitre.',
    longDesc:
      'En la calle Iquique del centro, una mansión de 1916 mantenía el estilo de los palacios construidos con la fortuna del salitre. Sus tres pisos, mansardas y patio interior con galerías eran típicos del barroco francés tardío. Sufrió daños en el terremoto de 1985 y fue parcialmente demolida. Subsiste su fachada.',
    yearStart: 1916,
    category: 'PATRIMONIO',
    era: 'PARLAMENTARISMO',
    latitude: -33.4373,
    longitude: -70.6649,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('arquitectura-salitre', 'Arquitectura del salitre en Santiago')],
  },

  // =========================================================================
  // RELLENO PRESIDENCIALISMO (1925-1973)
  // =========================================================================
  {
    slug: 'sitio-edificio-caja-ahorros-1935',
    title: 'Edificio Caja Nacional de Ahorros',
    shortDesc: 'Sede inaugurada en 1935 en Bandera, ejemplo del art decó financiero.',
    longDesc:
      'El edificio de la Caja Nacional de Ahorros, en Bandera con Compañía, se inauguró en 1935. Diseño art decó de Smith Solar y Smith Miller. Su fachada de granito y entradas con bajorrelieves alegóricos lo hicieron emblemático. Fue absorbida por el Banco del Estado en 1953. Sigue siendo edificio bancario.',
    yearStart: 1935,
    category: 'ECONOMIA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4391,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('caja-ahorros', 'Caja Nacional de Ahorros')],
  },
  {
    slug: 'sitio-banco-estado-1953',
    title: 'Banco del Estado de Chile',
    shortDesc: 'Fundado en 1953 por fusión de Caja de Crédito y Caja Nacional de Ahorros.',
    longDesc:
      'El Banco del Estado de Chile (BancoEstado) fue creado por la Ley 11.474 del 25 de agosto de 1953, fusionando la Caja de Crédito Hipotecario, la Caja Nacional de Ahorros y la Caja de Crédito Agrario. Su sede principal en Bandera 84 ocupa el antiguo edificio de la Caja Nacional. Es el único banco estatal del país.',
    yearStart: 1953,
    dateText: '25 de agosto de 1953',
    category: 'ECONOMIA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4391,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('banco-estado', 'BancoEstado')],
  },
  {
    slug: 'sitio-conjunto-portales-1968',
    title: 'Remodelación Republicana - Villa Portales',
    shortDesc: 'Conjunto habitacional moderno inaugurado en 1968 por la CORVI.',
    longDesc:
      'La Villa Portales en Estación Central fue inaugurada en 1968 por la Corporación de la Vivienda (CORVI). Diseño de BVCH (Bresciani, Valdés, Castillo, Huidobro), uno de los conjuntos modernos más importantes de Latinoamérica. Sus 1.860 departamentos en bloques con pasarelas inspiraron arquitectura social en toda la región. Es Monumento Nacional desde 2010.',
    yearStart: 1968,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4514,
    longitude: -70.6889,
    region: 'Metropolitana',
    comuna: 'Estación Central',
    sources: [CMN('Villa Portales', 2010)],
  },
  {
    slug: 'sitio-unidad-vecinal-providencia',
    title: 'Unidad Vecinal Providencia',
    shortDesc: 'Conjunto residencial moderno inaugurado en 1956.',
    longDesc:
      'La Unidad Vecinal Providencia, en Carlos Antúnez con avenida Providencia, fue inaugurada en 1956 por iniciativa del arquitecto Carlos Bresciani. Inspirado en las "unités d\'habitation" de Le Corbusier. 11 bloques con 1.000 departamentos, plazas, comercios y guardería. Es uno de los conjuntos modernos más importantes del Santiago.',
    yearStart: 1956,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4283,
    longitude: -70.6164,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [ARQ('La modernidad en Chile', 'Humberto Eliash', 1989)],
  },
  {
    slug: 'sitio-mun-fundacion-las-condes-1901',
    title: 'Fundación de la comuna Las Condes',
    shortDesc: 'Las Condes se constituye como comuna en 1901, antes parte de Ñuñoa.',
    longDesc:
      'La comuna de Las Condes fue creada por decreto del 22 de diciembre de 1901, separándose de Ñuñoa. Su nombre proviene de los condes de Sierra Bella, propietarios coloniales de la zona. Era zona rural con haciendas hasta los 60. Hoy es uno de los polos comerciales y residenciales más importantes del país.',
    yearStart: 1901,
    dateText: '22 de diciembre de 1901',
    category: 'POLITICA',
    era: 'PARLAMENTARISMO',
    latitude: -33.4128,
    longitude: -70.5728,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    sources: [MC('las-condes', 'Historia de Las Condes')],
  },
  {
    slug: 'sitio-poblacion-juan-antonio-rios',
    title: 'Población Juan Antonio Ríos',
    shortDesc: 'Conjunto habitacional de 1953-58, símbolo de la política de vivienda social.',
    longDesc:
      'La Población Juan Antonio Ríos en Independencia fue construida entre 1953 y 1958 por la Corporación de la Vivienda. Lleva el nombre del Presidente del Frente Popular fallecido en 1946. 4.000 viviendas distribuidas en bloques y casas pareadas, marcó el inicio de la masificación de la vivienda social en Chile.',
    yearStart: 1958,
    category: 'POLITICA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4133,
    longitude: -70.65,
    region: 'Metropolitana',
    comuna: 'Independencia',
    sources: [MC('jar', 'Población Juan Antonio Ríos')],
  },

  // =========================================================================
  // EDIFICIOS DICTADURA (1973-1990)
  // =========================================================================
  {
    slug: 'sitio-edificio-anaconda-1976',
    title: 'Antiguo edificio Anaconda',
    shortDesc: 'Sede de la Anaconda Copper en Santiago, vendida tras la nacionalización.',
    longDesc:
      'En la Alameda con calle MacIver, el antiguo edificio de la Anaconda Mining Company funcionaba como sede de la mayor empresa minera norteamericana operando en Chile hasta la nacionalización del cobre por Allende (1971). Tras la indemnización, el edificio pasó a otras empresas. Conserva fachada original.',
    yearStart: 1925,
    category: 'ECONOMIA',
    era: 'PARLAMENTARISMO',
    latitude: -33.443,
    longitude: -70.6489,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [BN('Cobre y nacionalización', 'Theodoro Moran', 1974)],
  },
  {
    slug: 'sitio-conjunto-villa-frei',
    title: 'Conjunto Villa Frei',
    shortDesc: 'Conjunto habitacional inaugurado en 1968 en Ñuñoa, ejemplo de vivienda media.',
    longDesc:
      'La Villa Presidente Frei en Ñuñoa fue inaugurada en 1968 como uno de los grandes conjuntos de la CORVI durante el gobierno de Eduardo Frei Montalva. 2.300 departamentos, áreas verdes, centro comercial y colegio. Diseño en torno al concepto de "ciudad jardín". Sigue siendo uno de los referentes de vivienda social masiva.',
    yearStart: 1968,
    category: 'PATRIMONIO',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4825,
    longitude: -70.5928,
    region: 'Metropolitana',
    comuna: 'Ñuñoa',
    sources: [MC('villa-frei', 'Villa Frei Ñuñoa')],
  },

  // =========================================================================
  // CONTEMPORÁNEO RECIENTE
  // =========================================================================
  {
    slug: 'sitio-anibal-pinto-2017',
    title: 'Edificio Aníbal Pinto (renovación)',
    shortDesc: 'Renovación de mansión histórica en Aníbal Pinto, completada en 2017.',
    longDesc:
      'La mansión de calle Aníbal Pinto, originalmente construida en 1912, fue renovada y abierta al público en 2017 como espacio cultural y eventos. Conserva su fachada y mampostería original. Es ejemplo de la regeneración del barrio Italia, en pleno auge gastronómico desde 2010.',
    yearStart: 2017,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4445,
    longitude: -70.6253,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('barrio-italia', 'Barrio Italia')],
  },
  {
    slug: 'sitio-barrio-italia-2010',
    title: 'Renacimiento del Barrio Italia',
    shortDesc: 'A partir de 2010 el Barrio Italia se transforma en polo gastronómico y de diseño.',
    longDesc:
      'El Barrio Italia, tradicional barrio de talleres mecánicos y mueblerías de los años 30-50, comenzó hacia 2010 una rápida transformación gastronómica y comercial. Las antiguas casonas se convirtieron en restaurantes, tiendas de diseño, anticuarios y galerías. Hoy es uno de los barrios más visitados por turistas y locales jóvenes.',
    yearStart: 2010,
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4453,
    longitude: -70.6203,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('italia', 'Barrio Italia')],
  },
  {
    slug: 'sitio-ciudad-empresarial-2000',
    title: 'Ciudad Empresarial',
    shortDesc: 'Polo empresarial en Huechuraba inaugurado en 2000.',
    longDesc:
      'Ciudad Empresarial, en la comuna de Huechuraba, fue desarrollada a partir de 2000 como polo de oficinas alternativas al centro y al sector oriente. Sus edificios de 6 a 10 pisos albergan call centers, multinacionales tecnológicas y servicios. Tiene parque, mall y restaurantes. Es el segundo polo empresarial de Santiago.',
    yearStart: 2000,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.3719,
    longitude: -70.6403,
    region: 'Metropolitana',
    comuna: 'Huechuraba',
    sources: [MC('ciudad-empresarial', 'Ciudad Empresarial')],
  },
  {
    slug: 'sitio-edificio-dgac-2018',
    title: 'Nueva Torre de Control Pudahuel',
    shortDesc: 'Torre de control de tráfico aéreo inaugurada en 2018.',
    longDesc:
      'La nueva Torre de Control de Pudahuel se inauguró en 2018, reemplazando la torre de 1967. Tiene 60 metros de altura y tecnología de última generación. Coordina más de 280.000 movimientos al año. Es operada por la DGAC.',
    yearStart: 2018,
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.3919,
    longitude: -70.7853,
    region: 'Metropolitana',
    comuna: 'Pudahuel',
    sources: [MC('torre-control', 'Torre de Control Pudahuel')],
  },
  {
    slug: 'sitio-puente-bicentenario-2009',
    title: 'Puente Bicentenario sobre el Mapocho',
    shortDesc: 'Puente vehicular y peatonal inaugurado en 2009 como obra del Bicentenario.',
    longDesc:
      'El Puente Bicentenario, en Vitacura, fue inaugurado en 2009 conectando el sector con Huechuraba. Diseño moderno con tirantes de acero. Lleva ese nombre por su construcción en preparación al Bicentenario. Es uno de los puentes más fotografiados sobre el Mapocho.',
    yearStart: 2009,
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.3964,
    longitude: -70.6,
    region: 'Metropolitana',
    comuna: 'Vitacura',
    sources: [MC('puente-bicentenario', 'Puente Bicentenario')],
  },
  {
    slug: 'sitio-metro-linea-6-2017',
    title: 'Línea 6 del Metro',
    shortDesc: 'Inaugurada el 2 de noviembre de 2017, conecta Cerrillos con Providencia.',
    longDesc:
      'La Línea 6 del Metro de Santiago se inauguró el 2 de noviembre de 2017. Tiene 15,3 km y 10 estaciones, conectando Cerrillos con Los Leones. Fue la primera línea totalmente automática (sin conductor) del país. Su construcción tomó 6 años. Lleva el morado como color identificatorio.',
    yearStart: 2017,
    dateText: '2 de noviembre de 2017',
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.4922,
    longitude: -70.7036,
    region: 'Metropolitana',
    comuna: 'Cerrillos',
    sources: [MC('metro-linea-6', 'Línea 6 del Metro')],
  },
  {
    slug: 'sitio-metro-linea-3-2019',
    title: 'Línea 3 del Metro',
    shortDesc: 'Inaugurada el 22 de enero de 2019, conecta Huechuraba con La Reina.',
    longDesc:
      'La Línea 3 del Metro de Santiago se inauguró el 22 de enero de 2019. Tiene 22 km y 18 estaciones, conectando Plaza de Quilicura (extensión 2023) con Fernando Castillo Velasco. Es la línea totalmente automática más larga del país y atraviesa varios barrios populares y comerciales.',
    yearStart: 2019,
    dateText: '22 de enero de 2019',
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.4225,
    longitude: -70.55,
    region: 'Metropolitana',
    comuna: 'La Reina',
    sources: [MC('metro-linea-3', 'Línea 3 del Metro')],
  },
  {
    slug: 'sitio-edificio-bicentenario-2011',
    title: 'Edificio Telefónica Movistar (Bicentenario)',
    shortDesc: 'Reformado en 2011 con renovación arquitectónica de fachadas.',
    longDesc:
      'En el Bicentenario, Telefónica Movistar reformó la fachada de su torre principal en Providencia con grandes pantallas LED y nueva iluminación. Marca el ascenso de los edificios "smart" en el centro corporativo. La iluminación variable se ha convertido en hito visual de las fiestas patrias y eventos urbanos.',
    yearStart: 2011,
    category: 'CIENCIA',
    era: 'TRANSICION',
    latitude: -33.4222,
    longitude: -70.6097,
    region: 'Metropolitana',
    comuna: 'Providencia',
    sources: [MC('movistar-bicentenario', 'Telefónica Movistar')],
  },
  {
    slug: 'sitio-mall-vivo-imperio-2016',
    title: 'Mall Vivo Imperio',
    shortDesc: 'Mall del centro de Santiago abierto en 2016 sobre el ex Cine Imperio.',
    longDesc:
      'El Mall Vivo Imperio, en Catedral con Bandera, abrió en 2016 sobre el solar del antiguo Cine Imperio (1932-1980). Combina comercio, cines y zonas gastronómicas. Es uno de los pocos malls del estricto casco histórico, en intento de reactivar el comercio del centro tradicional.',
    yearStart: 2016,
    category: 'ECONOMIA',
    era: 'TRANSICION',
    latitude: -33.4373,
    longitude: -70.6519,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('vivo-imperio', 'Mall Vivo Imperio')],
  },
  {
    slug: 'sitio-cementerio-parque-recoleta',
    title: 'Cementerio Parque Recoleta',
    shortDesc: 'Cementerio privado abierto en 1989 en Lo Barnechea.',
    longDesc:
      'El Cementerio Parque Recoleta abrió en 1989 en las faldas precordilleranas de Lo Barnechea. Modelo "parque" inspirado en cementerios estadounidenses, con sepulturas de césped y memoriales planos. Marcó la consolidación de los cementerios privados en Chile. Hoy es uno de los más usados por familias del oriente.',
    yearStart: 1989,
    category: 'PATRIMONIO',
    era: 'DICTADURA',
    latitude: -33.3614,
    longitude: -70.5039,
    region: 'Metropolitana',
    comuna: 'Lo Barnechea',
    sources: [MC('parque-recoleta', 'Cementerio Parque Recoleta')],
  },
  {
    slug: 'sitio-edificio-portales-2009',
    title: 'Renovación del entorno La Moneda',
    shortDesc: 'Plaza de la Ciudadanía remodelada en 2005 para revalorizar La Moneda.',
    longDesc:
      'En 2005, durante el gobierno de Lagos, se reformuló el entorno del Palacio de La Moneda con la Plaza de la Ciudadanía: explanada subterránea, peatonalización de calles laterales y la Plaza adyacente. El Centro Cultural La Moneda, bajo la plaza, abrió ese mismo año.',
    yearStart: 2005,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.444,
    longitude: -70.6536,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('plaza-ciudadania', 'Plaza de la Ciudadanía')],
  },
  {
    slug: 'sitio-centro-cultural-la-moneda',
    title: 'Centro Cultural La Moneda',
    shortDesc: 'Inaugurado en enero 2006, primer espacio cultural bajo La Moneda.',
    longDesc:
      'El Centro Cultural La Moneda fue inaugurado el 26 de enero de 2006 bajo la Plaza de la Ciudadanía. Diseñado por Cristián Undurraga. Tiene 7.200 m² subterráneos con 2 salas de exposición, cineteca nacional y tienda. Por sus salas han pasado retrospectivas de Picasso, Klimt, arte egipcio, Dalí. Recibe 700.000 visitantes al año.',
    yearStart: 2006,
    dateText: '26 de enero de 2006',
    category: 'CULTURA',
    era: 'TRANSICION',
    latitude: -33.4445,
    longitude: -70.6536,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('cultural-moneda', 'Centro Cultural La Moneda')],
  },

  // =========================================================================
  // SITIOS UNIVERSITARIOS Y EDUCATIVOS RECIENTES
  // =========================================================================
  {
    slug: 'sitio-uadolfo-ibanez-2009',
    title: 'Campus Peñalolén Universidad Adolfo Ibáñez',
    shortDesc: 'Campus inaugurado en 2009, obra emblemática de Rafael Moneo en Chile.',
    longDesc:
      'El Campus Peñalolén de la Universidad Adolfo Ibáñez, en Diagonal Las Torres con Avenida Las Tinajas, fue diseñado por el arquitecto español Rafael Moneo (Pritzker 1996) e inaugurado en 2009. Es la única obra de Moneo en Chile. Sus volúmenes de hormigón y madera, con plazas escalonadas, lo hacen referente arquitectónico.',
    yearStart: 2009,
    category: 'CIENCIA',
    era: 'TRANSICION',
    latitude: -33.4853,
    longitude: -70.5183,
    region: 'Metropolitana',
    comuna: 'Peñalolén',
    sources: [ARQ('Rafael Moneo en Chile', 'Smiljan Radic', 2010)],
  },
  {
    slug: 'sitio-edificio-corparaucania',
    title: 'Edificio Innovación UC',
    shortDesc: 'Centro de innovación de la Universidad Católica inaugurado en 2014 en San Joaquín.',
    longDesc:
      'El Centro de Innovación UC Anacleto Angelini fue inaugurado en 2014 en el Campus San Joaquín. Diseño de Alejandro Aravena (Pritzker 2016). Se ha convertido en ícono arquitectónico chileno por su volumen de hormigón y su patio interior cubierto. Es referente en innovación y emprendimiento universitario.',
    yearStart: 2014,
    category: 'CIENCIA',
    era: 'TRANSICION',
    latitude: -33.4978,
    longitude: -70.6133,
    region: 'Metropolitana',
    comuna: 'Macul',
    featured: true,
    sources: [ARQ('Alejandro Aravena, Elemental', 'Alejandro Aravena', 2018)],
  },
  {
    slug: 'sitio-villa-san-luis-2017',
    title: 'Memorial Villa San Luis',
    shortDesc: 'Memorial inaugurado en 2017 en el sitio de la Villa San Luis derribada en dictadura.',
    longDesc:
      'La Villa San Luis fue un conjunto habitacional construido por la Unidad Popular para 1.038 familias obreras en Las Condes (1972). En 1978-79 la dictadura desalojó violentamente a sus habitantes y demolió 80% de los bloques. En 2017, tras décadas de litigios, el Memorial Villa San Luis fue inaugurado en el sitio. Es Monumento Histórico desde 2017.',
    yearStart: 1972,
    yearEnd: 1979,
    category: 'POLITICA',
    era: 'PRESIDENCIALISMO',
    latitude: -33.4133,
    longitude: -70.6058,
    region: 'Metropolitana',
    comuna: 'Las Condes',
    featured: true,
    sources: [CMN('Villa San Luis', 2017)],
  },

  // =========================================================================
  // SITIOS PERIFÉRICOS (sur, poniente)
  // =========================================================================
  {
    slug: 'sitio-iglesia-renca-1796',
    title: 'Iglesia de Renca',
    shortDesc: 'Templo construido en 1796, da nombre a la comuna de Renca.',
    longDesc:
      'La Iglesia Matriz de Renca fue construida en 1796 sobre una antigua capilla colonial. Reconstruida tras los terremotos del XIX. Su edificación actual data de 1925 conservando elementos del XVIII. Le da nombre a la comuna y es centro de la festividad de Cruz de Mayo. Monumento Nacional.',
    yearStart: 1796,
    category: 'RELIGION',
    era: 'COLONIA',
    latitude: -33.4067,
    longitude: -70.7322,
    region: 'Metropolitana',
    comuna: 'Renca',
    sources: [CMN('Iglesia Renca', 1985)],
  },
  {
    slug: 'sitio-laguna-carén',
    title: 'Parque Laguna Carén',
    shortDesc: 'Parque científico y recreativo de 1.000 hectáreas en Pudahuel.',
    longDesc:
      'El Parque Laguna Carén, en Pudahuel, ocupa 1.000 hectáreas y alberga el Centro Internacional de Conferencias Espacio Riesco, parques científicos universitarios y áreas verdes. Su laguna artificial es uno de los espejos de agua más grandes de la zona urbana. Proyecto en desarrollo desde los 90.',
    yearStart: 1995,
    category: 'CIENCIA',
    era: 'TRANSICION',
    latitude: -33.4842,
    longitude: -70.7861,
    region: 'Metropolitana',
    comuna: 'Pudahuel',
    sources: [MC('caren', 'Parque Laguna Carén')],
  },
  {
    slug: 'sitio-aluvion-san-jose-1987',
    title: 'Aluvión de San José de Maipo de 1987',
    shortDesc: 'Aluvión de mayo de 1987 destruye gran parte de San José de Maipo.',
    longDesc:
      'El 1 de mayo de 1987, un aluvión por intensas lluvias en cordillera arrasó gran parte de San José de Maipo y comunidades del Cajón del Maipo. Murieron 41 personas y desaparecieron 28. Causó pérdidas valoradas en millones de dólares. Llevó a estudios de ordenamiento territorial cordillerano.',
    yearStart: 1987,
    dateText: '1 de mayo de 1987',
    category: 'DESASTRE_NATURAL',
    era: 'DICTADURA',
    latitude: -33.6433,
    longitude: -70.3528,
    region: 'Metropolitana',
    comuna: 'San José de Maipo',
    sources: [MC('aluvion-1987', 'Aluvión de San José de Maipo')],
  },

  // =========================================================================
  // FUTURO INMEDIATO
  // =========================================================================
  {
    slug: 'sitio-portal-bicentenario-cerrillos',
    title: 'Portal Bicentenario Cerrillos',
    shortDesc: 'Megaproyecto urbano sobre los terrenos del antiguo aeropuerto Los Cerrillos.',
    longDesc:
      'El Portal Bicentenario Cerrillos es un proyecto de ciudad satélite sobre las 245 hectáreas del antiguo aeropuerto Los Cerrillos (cerrado en 2006). Incluye torres residenciales, áreas comerciales, parque urbano, biblioteca, museo de la Aviación y conexión con la Línea 6 del Metro. En desarrollo gradual desde 2010.',
    yearStart: 2010,
    category: 'PATRIMONIO',
    era: 'TRANSICION',
    latitude: -33.4892,
    longitude: -70.7028,
    region: 'Metropolitana',
    comuna: 'Cerrillos',
    sources: [MC('cerrillos-bicentenario', 'Portal Bicentenario Cerrillos')],
  },
  {
    slug: 'sitio-bus-electrico-2018',
    title: 'Primer bus eléctrico del transporte público',
    shortDesc: 'En diciembre 2018 entran en operación los primeros buses eléctricos del Transantiago.',
    longDesc:
      'El 14 de diciembre de 2018 entraron en operación los primeros 100 buses eléctricos del transporte público de Santiago. Importados de China (BYD), operan en el corredor Vicuña Mackenna. Hoy Chile tiene la mayor flota de buses eléctricos urbanos fuera de China, con más de 2.000 unidades.',
    yearStart: 2018,
    dateText: '14 de diciembre de 2018',
    category: 'TRANSPORTE',
    era: 'TRANSICION',
    latitude: -33.4456,
    longitude: -70.633,
    region: 'Metropolitana',
    comuna: 'Santiago',
    sources: [MC('bus-electrico', 'Buses eléctricos en Santiago')],
  },
]

export const SANTIAGO_MODERNOS_VERSION = '0.1.0'
